### ISSUE TITLE
[Google Cloud Storage Connector] : Unable to create an index in Elasticsearch when using GCS as native connector

### ISSUE THREAD

**Issue by prashant-elastic** [elastic/connectors#1168]
## Bug Description
Unable to create an index in Elasticsearch when using GCS as native connector

### To Reproduce
1. Go to 'Elasticsearch Cloud instance'
2. Create an index using 'Use a connector' option
3. Select 'Google Cloud Storage' and click on 'Continue'
4. Enter name of the index and click on 'Create index'

## Expected behavior
An index should be created successfully with Google Cloud Storage as native connector

## Actual behavior
An error appears as "We were not able to create your index"

## Screenshots
![image (6)](https://github.com/elastic/connectors-python/assets/103035276/f03ccfcb-b946-48c6-ae65-120fb3db6207)

## Environment

- Elastic Cloud v8.9.0-SNAPSHOT
- Browser [Chrome v114.0.5735.199]

**Comment by prashanttest-elastic** [comment]
@danajuratoni Can you please ask someone from the team to take a look into this issue? It still exists in v8.9.0-latest and v8.10.0-SNAPSHOT cloud instance

**Comment by khushbu-elastic** [comment]
@danajuratoni Please let us know if there are any updates on this issue.

**Comment by prashant-elastic** [comment]
@danajuratoni Can you please ask someone from the team to take a look into this issue? It still exists in v8.9.0-latest and v8.10.0-SNAPSHOT cloud instance?
