### ISSUE TITLE
Add some site metadata to each object synced by Sharepoint Online connector

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#1217]
Currently there seems to be no easy way to query objects only for specific site for Sharepoint Online connector.

We can add reference to parent site object into each synced object, the format of the parent site object could be:

```json
{
  "id": "something.sharepoint.com,guid, guid",
  "name": "my nice website"
}
```

**Comment by seanstory** [comment]
Drive items get a `parent_reference` field like:
```
{
  "path": "/drives/b!TqCnzOK5oEuJ1qYWXHpVuJgMoZsTqNdLuEAXMQ7Tz-aNoc_D1tmNRoskOwQLBRoh/root:",
  "driveId": "b!TqCnzOK5oEuJ1qYWXHpVuJgMoZsTqNdLuEAXMQ7Tz-aNoc_D1tmNRoskOwQLBRoh",
  "driveType": "documentLibrary",
  "siteId": "cca7a04e-b9e2-4ba0-89d6-a6165c7a55b8",
  "id": "01ZNLSM456Y2GOVW7725BZO354PWSELRRZ"
}
```

But lists, list items, and site pages don't have something similar. And even this `parent_reference` doesn't have anything human-readable in it. 

Though all of these have `webUrl`, which seems to work fine for this. For example, this query returns everything in the `Sean'sTeamSite/sean'ssubsite` site:

```
GET search-sharepoint/_search
{
  "query": {
    "wildcard": {
      "webUrl.enum": {
        "value": "https://enterprisesearch.sharepoint.com/sites/Sean%27sTeamSite/sean%27ssubsite/*"
      }
    }
  }
}
```

What's the use case you have in mind, @artem-shelkovnikov? Do you still feel that this ticket is needed?

**Comment by artem-shelkovnikov** [comment]
@seanstory it was reported by @llermaly originally - making it possible to search for "all documents that contain the word `something` on the sites a, b and c" - so purely for searching data.

**Comment by seanstory** [comment]
Gotcha. I haven't heard any customer's reiterate this, and since I can accomplish that type of search currently using `webUrl`, I'm gonna close it for now. We've kept a pattern of returning data as the 3rd-party returns it, and I'd prefer to keep that unless there's a really strong reason to augment it with our own idea of what should be included.
