### ISSUE TITLE
Python Mongo Connector 8.8 does not support SSL

### ISSUE THREAD

**Issue by deveshkp** [elastic/connectors#1427]
I am unable to connect to MongoDB if Mongo is ssl enabled.

I tried to connect to Mongo with SSL disabled and am able to connect but with SSL enabled, connector timing out.

**Comment by seanstory** [comment]
Hi @deveshkp - can you share any relevant logs and/or stack traces? What version of MongoDB are you using, or are you using Mongo Atlas? And is the Certificate protecting your mongo host a self-signed cert or a cert signed by a custom Certificate Authority?

**Comment by seanstory** [comment]
Closing as we haven't heard back from you, and there have been a number of recent changes to Mongo related to SSL, so this seems unlikely to be an issue anymore. Please don't hesitate to re-open if you have more details/questions/concerns.
