### ISSUE TITLE
Discovery on alternate packaging for "enterprise" python projects

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#1491]
### Problem Description
Enterprise software is usually downloaded as an artifact. TAR, Zip, RPM, DEB, DMG, etc. Python doesn't seem to have a really popular artifact for distribution. There's PyPI ([separate investigation](https://github.com/elastic/connectors-python/issues/1490)) for distributing SDIST ("source distribution" source code zip files) and Wheels (zip files of pre-built/compiled code). But these can't execute in a vacuum - you need to separately set up a python environment, install other dependencies, and only then can run these. 

It would be nice to produce an artifact that packaged all the dependencies for our project. Right now we produce a docker image, but that's an artifact that contains not only our code and dependencies, but also a python distribution, an operating system, and a whole container. There's got to be a better middle ground.

### Proposed Solution
Do some research into other python package options, the build tools to create them, and the associated pros and cons.
Start with: https://packaging.python.org/en/latest/overview/

Outcomes of this discovery should be a minimal writeup of the various options, weighing the pros and cons, and a recommendation on next steps.

Let's not sink more than 5 days into this discovery.

**Comment by artem-shelkovnikov** [comment]
Let's just close this?
