### ISSUE TITLE
Make ftest for oracle connector work on aarch64

### ISSUE THREAD

**Issue by praveen-elastic** [elastic/connectors#1579]
### Problem Description

oracle image being used in oracle connector ftest is not supported in aarch64 due to which it is skipped in aarch64 nightly for now. We need to come up with a solution to make it work on aarch64 nightly too.

**Comment by acrewdson** [comment]
@praveen-elastic 👋 over [here](https://github.com/elastic/connectors/issues/1853) I mentioned we could consider adopting a different Oracle image. That image is `linux/amd64` but works fine on, for instance, apple silicon macbooks when you set `--platform linux/amd64`.

**Comment by praveen-elastic** [comment]
Thanks @acrewdson, I'll look into it and update the ftest.

**Comment by acrewdson** [comment]
Looks like Oracle only publishes arm64 images for one version of their product (19):
> `docker pull container-registry.oracle.com/database/enterprise:19.19.0.0`

However you can't pull that image without first authenticating with their container registry, and that requires creating an Oracle account. We could consider pulling the image from their registry and then storing it in our internal container registry for use in CI pipelines. I can look into that soon.

**Comment by artem-shelkovnikov** [comment]
Can we close this issue?

**Comment by praveen-elastic** [comment]
Sure, closing the issue. @acrewdson feel free to reopen if you have any concern
