### ISSUE TITLE
Improve Jira performance when DLS enabled

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1642]
### Problem Description
When DLS is enabled, we see a significant performance degradation in full syncs. 

### Proposed Solution
Research improvement options to remove the current bottlenecks.

Followup on 8.10 DLS ticket from [this discussion](https://github.com/elastic/connectors-python/issues/1291#issuecomment-1710739422).

**Comment by danajuratoni** [comment]
cc: @DianaJourdan @timgrein @seanstory moved the Jira discussion in this ticket to follow up on for 8.11

**Comment by moxarth-elastic** [comment]
@danajuratoni The rate limit for Atlassian Jira apis is too poor i.e. 500 requests per 5 minutes. Refer the [rate limit documentation](https://developer.atlassian.com/server/hipchat/hipchat-rest-api-rate-limits/) for more info. we tried to tweak few connector parameter that may affect the performance, but due to the rate-limit connection is performing slow.

Do you have any feedback on it?

**Comment by khushbu-elastic** [comment]
@danajuratoni @DianaJourdan Do we have any update on this?

**Comment by danajuratoni** [comment]
@DianaJourdan @seanstory we can close this ticket if we've reached technical limitations that make additional performance improvements not feasible at this time.

**Comment by prashanttest-elastic** [comment]
@DianaJourdan @seanstory Please check this and update the status accordingly.

**Comment by khushbu-elastic** [comment]
@DianaJourdan @seanstory Please check this & update the status accordingly.

**Comment by seanstory** [comment]
Has anyone filed a support issue or community forum post with Atlassian to see if there's a more efficient way to retrieve the necessary data in fewer requests?

**Comment by moxarth-elastic** [comment]
I've started a discussion in the Atlassian community - https://community.atlassian.com/t5/Jira-discussions/Do-we-have-a-more-efficient-way-to-fetch-the-permissions-for/m-p/2546267#M21713.

**Comment by moxarth-elastic** [comment]
@seanstory There were no comments/answers for the community question i shared above and recently the Atlassian support team has closed the comment section. 

Since, there are no updates on it, can we close this ticket?

**Comment by seanstory** [comment]
Since they didn't respond to a community post, I suggest that we file an official support ticket with them: https://support.atlassian.com/contact/#/

**Comment by moxarth-elastic** [comment]
@seanstory even the support page is redirecting me to raise a question/community post which we already did earlier. However, i've raised another question concerning the same - https://community.atlassian.com/t5/Jira-Software-questions/Finding-a-more-efficient-way-to-fetch-the-users-associated-with/qaq-p/2571340#M657594.

**Comment by seanstory** [comment]
<img width="489" alt="Screenshot 2024-01-05 at 1 55 45 PM" src="https://github.com/elastic/connectors/assets/5288246/83b00d5d-be05-4f33-b9b2-aaa0ce5892b2">

Well that sucks. I assume you're using a 10-user license account?

**Comment by moxarth-elastic** [comment]
@seanstory i've created a new Atlassian account with premium subscription and tried to generate a support request. It got created successfully, let's wait for the support team to reach out to me.

**Comment by moxarth-elastic** [comment]
@seanstory Atlassian support engineer has provided a suggestion to make our approach more optimal but those are the exact same steps we are following for fetching permissions. You can take a look at their comments in the support ticket - https://support.atlassian.com/requests/PCS-243056/.
Please let me know your thoughts on this.

**Comment by seanstory** [comment]
Perfect, thanks @moxarth-elastic. With that research done, we can be more confident in explaining to any Jira DLS customers who complain about performance that this is a bottleneck on Jira's APIs, and know that we didn't leave any stone unturned.

**Comment by seanstory** [comment]
At this point, I think it's safe to close this issue, since we've done our due diligence, even though we have not found any wins for improving performance. Please feel free to re-open if you disagree.
