### ISSUE TITLE
Use url-encoded value when using Google Cloud Storage objects get API

### ISSUE THREAD

**Issue by bhodorog** [elastic/connectors#1695]
## Bug Description
The current google_cloud_storage.py is using url-**un**encoded object names to fetch the content of those objects, hence the request to https://cloud.google.com/storage/docs/json_api/v1/objects/get will fail with an HTTP 404 error. 
The official docs are also recommending url-encoding the value of the `object` parameter

> object	string	Name of the object. For information about how to URL encode object names to be path safe, see [Encoding URI path parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).

Now after digging a bit into both `connectors-python` and `aiogoogle` (the library used to interact with GCP apis) I managed to dig out the following relevant issue: https://github.com/omarryhan/aiogoogle/pull/115. Which basically means currently `connectors-python` is not properly using `aiogoogle` library's API.

Basically this line [here](https://github.com/elastic/connectors-python/blob/a04413ae61026242f83319699b053f0910068569/connectors/sources/google_cloud_storage.py#L399C33-L399C33) is passing the un-quoted value of the object name (I assume since for a brief moment that's how aiogoogle library was working). The direct effect of that is that the object name won't be encoded at all and requiest for objects having `/` in their names (e.g. `foo/bar.txt`) won't be quoted resulting in a 404 from google's apis.

Now the fix should be trivial, when calling `objects get` api  passing to aiogoole  the `params_safe_chars` argument, such as
```python
                self._google_storage_client.api_call(
                    resource="objects",
                    method="get",
                    bucket=blob["bucket_name"],
                    object=blob_name,
                    alt="media",
                    userProject=self._google_storage_client.user_project_id,
                    pipe_to=async_buffer,
                    path_params_safe_chars={"object": "'"},
                )
```
Note I used the same `safe=` characters as used [here](https://github.com/elastic/connectors-python/blob/a04413ae61026242f83319699b053f0910068569/connectors/sources/google_cloud_storage.py#L344)

### To Reproduce
1. Create an object in a GoogleCloudStorage bucket having a `/` character in its name, e.g. `foo/bar.txt`
2. Set up a GoogleCloudStorage connector as per https://www.elastic.co/guide/en/enterprise-search/current/connectors-google-cloud.html
3. Check the logs of the deployed GoogleCloudStorage connector for errors such as:
```
Request URL:
https://storage.googleapis.com/storage/v1/b/some-bucket-of-your-choice/o/foo/bar.txt?alt=media&userProject=my-google-project
[FMWK][15:39:29][WARNING] [Connector id: BUvl0YoBy8Y0OkIIQrgH, index name: search-google-cloud-storage, Sync job id: fktJ14oBy8Y0OkII0bgr] Retry count: 3 out of 3. Exception:

Not Found
```

## Expected behavior
Objects having `/` in their name should be fetched successfully from google cloud storage using urls of this form:
```
https://storage.googleapis.com/storage/v1/b/some-bucket-of-your-choice/o/foo%2Fbar.txt?alt=media&userProject=my-google-project
```

## Screenshots
none

## Environment

- OS: Debian GNU/Linux 12 (bookworm)
- Browser: none, not browser related
- Version:
```
/app# /app/bin/pip list | grep elastic
elastic-transport        8.4.0
elasticsearch            8.8.0
elasticsearch-connectors 8.11.0.0    /app
```
elasticsearch-connectors 8.11.0.0    /app <-- built from https://github.com/elastic/connectors-python/commit/81bd5b6

## Additional context
Connector logs:
```
Request URL:
https://storage.googleapis.com/storage/v1/b/some-bucket-of-your-choice/o/foo/bar.txt?alt=media&userProject=my-google-project
[FMWK][15:39:29][WARNING] [Connector id: BUvl0YoBy8Y0OkIIQrgH, index name: search-google-cloud-storage, Sync job id: fktJ14oBy8Y0OkII0bgr] Retry count: 3 out of 3. Exception:

Not Found
```

**Comment by seanstory** [comment]
Thanks @bhodorog for the detailed and clear report! We'll get this prioritized in our backlog. CC @danajuratoni

**Comment by abhishekjoshi-crest** [comment]
Hi, @bhodorog In GCS we cannot create file contains `/` in name. However, I was able to create file with full name as `folder_name/file_name` only if i create it inside the folder. Doing so reproduces this issue. Are you referring to this scenario ?
Let me know if it is anything else.

**Comment by khushbu-elastic** [comment]
@danajuratoni @seanstory We have checked this and found that we have pinned the version of aiogoogle to 4.5.0 and it was working fine but after upgrading it to aiogoogle to 5.3.0,  we started facing this issue. 
However we are working on it and will raise the PR for the fix soon.

**Comment by bhodorog** [comment]
> Hi, @bhodorog In GCS we cannot create file contains `/` in name. However, I was able to create file with full name as `folder_name/file_name` only if i create it inside the folder. Doing so reproduces this issue. Are you referring to this scenario ? Let me know if it is anything else.

Hi @abhishekjoshi-crest ... while my reply is late, since you've already figured it out (and fixed it... thank you very much :) ), just to answer your question. There are no "folders", nor "files" in Google Cloud Storage. There are only objects. And typically an object is a file. As noted in the official docs: https://cloud.google.com/storage/docs/objects `/` is an allowed character in the GCS object name, which is often used to simulate a directory hierarchy, although there are no directories per se :).

**Comment by abhishekjoshi-crest** [comment]
Cool, Thanks !
