### ISSUE TITLE
Salesforce testing

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1708]
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix
- [x] Compatibility tests for running connector as native in Cloud

**Comment by khushbu-elastic** [comment]
@danajuratoni @DianaJourdan  We have checked the Indexing & Deindexing functionalities for Salesforce connector and it seems working fine. We have checked the same in different OS. It is working fine as Native connector in Cloud. We can mark the above tasks as Done and close this issue.
