### ISSUE TITLE
Cancel pending syncs

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#1723]
### Problem Description
Right now, if you trigger a bunch of syncs, you can't cancel the pending syncs. You can only cancel the currently in-progress sync. We should either not allow you to have multiple pending syncs, or should give users a way to cancel syncs that are pending.

### Proposed Solution
- [ ] have "cancel sync" cancel all syncs running _and_ pending
- [ ] OR, not let you have more than one pending sync at a time.

### Additional Context
Relates to https://github.com/elastic/connectors-python/issues/1722

**Comment by danajuratoni** [comment]
Closing as done, this will be included in 8.14
