### ISSUE TITLE
[SQL Servers] Support ingestion of SQL views

### ISSUE THREAD

**Issue by jedrazb** [elastic/connectors#1761]
## Bug Description

MySQL (and any other SQL server-based connector) is unable to ingest any view because SQL servers don't associate primary keys with views.

### To Reproduce

Create a view in mysql, e.g. join some data:

```
CREATE VIEW user_orders_view AS
SELECT users.name, orders.product_name, orders.order_date
FROM users
JOIN orders ON users.id = orders.user_id;

```

1. Setup connector
2. Add `user_orders_view` table to connector config 
3. Try to sync the data
4. See error in logs:

```
 Skipping table user_orders_view from database mydb since no primary key is associated with it. Assign primary key to the table to index it in the next sync interval.
```

Views in mysql can't have primary keys assigned

## Expected behavior

It would be great from UX perspective to create a view from a complex query and ingest it via the connector - vs. doing it via advanced sync rule.

**Comment by artem-shelkovnikov** [comment]
It kinda makes sense, though, right?

This view has no key, thus we cannot determine the id for it. What's our plan for id support?

**Comment by jedrazb** [comment]
Could we perhaps let users manually specify columns to create a composite (primary) key? Like in this case the pkey is user_id, order_id. 

Alternative to that, is writing a complex advanced sync rule to materialize this view and ingest it.

**Comment by jedrazb** [comment]
In order to meet the primary key constraint we need to use physical table with a primary key constraint defined, not a view - which is not ideal because this physical table needs to be rebuilt periodically to stay "fresh" with source tables.

It seems that advanced sync rules are the way to go!

**Comment by moxarth-elastic** [comment]
Hi @jedrazb @max-zirkonzahn 
to fix this issue specifically for the MySQL connector, we need to create a VIEW as per the following query:
```
CREATE VIEW user_orders_view_with_pk AS
      SELECT
      CONCAT(users.id, '-', orders.id) AS synthetic_pk,
      users.name,
      orders.product_name,
      orders.order_date
FROM users
JOIN orders ON users.id = orders.user_id;
``` 
we've added a column for the synthetic_pk which will be used in the advanced sync rules as below:

```
[
  {
    "tables": [
      "user_orders_view_with_pk"
    ],
    "query": "SELECT synthetic_pk, name, product_name, order_date FROM user_orders_view_with_pk",
    "id_columns": [
      "synthetic_pk"
    ]
  }
]
```

**Comment by moxarth-elastic** [comment]
@jedrazb closing this issue as all attached PRs have been merged. Feel free to reopen it in case of any issue.
