### ISSUE TITLE
[SPO] Incremental sync doesn't detect document deletes

### ISSUE THREAD

**Issue by jedrazb** [elastic/connectors#1822]
## Bug Description

Incremental sync should be able to detect documents that were added, edited or deleted. 

It works for insertions and edits. Deletes are not detected at all right now.

I tested deletes with: subsite, site_page, list, list_item, site_drive or list_item_attachment.

### To Reproduce
1. Configure SPO connector
2. Run connector service locally
3. Perform full sync
4. Add any document type (subsite, site_page, list, list_item, site_drive or list_item_attachment)
5. Run incremental sync
6. Observe that added/edited docs are inserted into the index
7. Delete any doc
8. Run incremental sync
9. Note "deleted docs" stays 0, document is still present in the index
10. Run full sync. Now it will detect deletes correctly

## Expected behavior

Incremental syncs should detect deletes correctly and apply the deletes to index.

## Screenshots

Here is my approach testing this. Note I ran full sync, I ran subsequently a few incremental syncs deleting different document types. I ran full sync at the end (only then the deletes were actually detected). 
<img width="1258" alt="Screenshot 2023-10-19 at 14 12 36" src="https://github.com/elastic/connectors/assets/14121688/9451cb18-99de-478d-b9ad-161bfc862e86">

**Comment by jedrazb** [comment]
This is an expected behaviour of incremental syncs for non drive-items. It's a "known limitation". Leaving this issue open but removing priority label.

**Comment by artem-shelkovnikov** [comment]
Should we close this issue?
