### ISSUE TITLE
Improve OneDrive performance when DLS enabled

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1832]
### Problem Description
When DLS is enabled, we see a significant performance degradation in full syncs as permissions are retrieved for each individual item.

### Proposed Solution
Research improvement options to optimize performance. 
One proposed improvement: [JSON batching](https://learn.microsoft.com/en-us/graph/json-batching)

Followup on [8.11 DLS ticket](https://github.com/elastic/connectors/issues/1592).

**Comment by praveen-elastic** [comment]
Raised a PR for performance improvement: https://github.com/elastic/connectors/pull/1916

**Comment by praveen-elastic** [comment]
Addressing Comments of the PR.
