### ISSUE TITLE
[Connectors][Docker] Use official release docker images in connector docs

### ISSUE THREAD

**Issue by jedrazb** [elastic/connectors#1843]
### Problem Description

Fix release image tags in elastic docs. Remove reference to `-SNAPSHOT` builds. It does not sound as a prod-ready image tag.

Reference in [elastic docs](https://github.com/elastic/enterprise-search-pubs/blob/main/enterprise-search-docs/_connectors-docker-instructions.asciidoc?plain=1#L61) see hardcoded SNAPSHOT. [See Deployment using Docker](https://www.elastic.co/guide/en/enterprise-search/current/connectors-google-drive.html#connectors-google-drive-deployment-using-docker) section step 3 for Google Drive connector.

Also in [elastic/connectors](https://github.com/elastic/connectors/blob/main/docs/DOCKER.md) repo we have references to -SNAPSHOT images in official guide.

**Comment by jedrazb** [comment]
Hi @leemthompo 👋 This might be a task for the user docs team. `-SNAPSHOT` prefix in docker images generally refers to a development build of the application or service, not on a released version. In the docker instructions for running connectors with docker as self-managed service we refer to image with snapshot prefix.

**Comment by leemthompo** [comment]
@jedrazb 

- Sounds right to remove SNAPSHOT from _user_ guides (I'll open PR)
- But maybe keep a reference to this option in the repo, given that folks might be working on main? WDYT? (Could still remove from the main example, but add a note mentioning the option)

**Comment by jedrazb** [comment]
Linking for visibility:
- https://github.com/elastic/enterprise-search-pubs/pull/3985

**Comment by leemthompo** [comment]
@jedrazb I think we can close this one?
