### ISSUE TITLE
[Connectors][Docker] Add "Run connectors with Docker" page to elastic docs

### ISSUE THREAD

**Issue by jedrazb** [elastic/connectors#1845]
### Problem Description

In Elastic docs about connectors we don’t have a separate page that follows the pattern Run X with Docker- like with other products at Elastic: [ES](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html), [Kibana](https://www.elastic.co/guide/en/kibana/current/docker.html), [Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html), [Logstash](https://www.elastic.co/guide/en/logstash/current/docker.html) etc. 

The google search query `run elastic connectors docker` suggests the [Connector clients | Enterprise Search documentation](https://www.elastic.co/guide/en/enterprise-search/current/build-connector.html) page, but in Google search results it’s not explicit that we have instructions for running with docker. In fact, in the “Run with docker” section, there is just a mention of the Docker.md file in the repository.

### Proposed Solution

Create "Run Elastic Connectors with Docker" docs page - that just consolidates docker commands that are scattered throughout our docs.

**Comment by leemthompo** [comment]
We do also have specific Docker deployment instructions for each connector client. [Example](https://www.elastic.co/guide/en/enterprise-search/current/connectors-google-cloud.html#connectors-google-cloud-docker).

We outline the two deployment options (`make` and Docker) for connector clients in the Elastic docs, but you're right we delegate to the repo for further details about Docker which isn't ideal.
Maybe we could just update the existing [Run with Docker](https://www.elastic.co/guide/en/enterprise-search/current/build-connector.html#build-connector-service-docker) section to include whatever we think is missing in the Elastic docs currently.

**Comment by leemthompo** [comment]
This does raise an interesting question about how folks actually use the docs in practice. Do they look for the general overview and then look at the reference for their connector of interest? Or do they dive into their data source of choice immediately and try to muddle through? Or do they shuttle between the docs and repo like headless chickens because the info is scattered everywhere? 😄
