### ISSUE TITLE
Advanced Rules for S3

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1885]
Enhance S3 with advanced sync rules support.

### Acceptance criteria

- [ ] discovery document with advanced sync rules for S3
- [ ] add support for advanced sync rules as defined in the discovery
- [ ] documentation with several examples illustrating the syntax, how a basic use case works, limitations
- [ ] document impact of advanced sync rules on connector configuration and on document indexing
- [ ] add tooltip on the configurable fields that are ignored when advanced sync rules are used, informing the user about the behavior. Text to be used as tooltip: "This configurable field is ignored when Advanced Sync Rules are used."

**Comment by akanshi-elastic** [comment]
Progress Summary [16th nov- 22nov]
S3
shared discovery document with advanced sync rules for S3

**Comment by akanshi-elastic** [comment]
Progress Summary [24th nov- 30th nov]
S3

1.PR got merged
2. Need to update readme for S3 as per this document examples: https://drive.google.com/drive/folders/1CGDOmYiYoIjwabrTq9jHG1r4o0olCLhr
@wangch079  Can you please update the [official documentaion](https://www.elastic.co/guide/en/enterprise-search/master/connectors-s3.html#connectors-s3-sync-rules) of S3?

**Comment by akanshi-elastic** [comment]
Reopen the ticket as Documentation PR is yet to be merged
