### ISSUE TITLE
DLS: GitHub

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1886]
Enhance GH with document level security.

### Acceptance criteria
- [x] Discovery document with DLS for GH
- [x] Add DLS support for GH as defined in the discovery
- [x] Functional tests performed
- [x] DLS documentation for GH
- [x] Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud
- [x] Updated docs

**Comment by parth-elastic** [comment]
@timgrein Shared discovery doc in the elastic drive - [[Reference](https://docs.google.com/document/d/1bw1KpngHQHBbHQ_NS5oNKDHpf5kqMtubGuQSLtwRffU/edit)]

cc: @danajuratoni @DianaJourdan

**Comment by parth-elastic** [comment]
Weekly status update [10 Nov 2023 to 16 Nov 2023]

- Explored the Github DLS 
- Shared the [discovery doc](https://docs.google.com/document/d/1bw1KpngHQHBbHQ_NS5oNKDHpf5kqMtubGuQSLtwRffU/edit)

**Comment by parth-elastic** [comment]
Weekly status update [17 Nov 2023 to 23 Nov 2023]


- Updated discovery doc with more details and in a structured manner. [Reference](https://docs.google.com/document/d/1bw1KpngHQHBbHQ_NS5oNKDHpf5kqMtubGuQSLtwRffU/edit)
- Started Implementation for Gtihub DLS 
- Internal Testing is ingoing 

We will be in good position to raise PR early next week

**Comment by parth-elastic** [comment]
Weekly status update [24 Nov 2023 to 30 Nov 2023]

- Implementation Completed
- Internal Testing Completed
- Raised a PR for the same [[Reference](https://github.com/elastic/connectors/pull/1923)]

**Comment by parth-elastic** [comment]
@leemthompo, We have added a few configurations in the GitHub connector, as shown below. Can you please update it on the GitHub documentation page?

#### `repo_type`
Dropdown to specify GitHub repository type: `Organization` or `Other`. In the case of `Organization` connector fetches documents of specific organization only. Default value is `Other`.

#### `org_name`
GitHub Organization name to fetch data from the GitHub instance. This field is only available if 'repo_type' is set to `Organization`.

**Comment by parthpuri-elastic** [comment]
@leemthompo Currently, in the [GitHub connector documentation](https://www.elastic.co/guide/en/enterprise-search/current/connectors-github.html) we have mentioned only the "repo" scope is required. But after DLS, the required scopes are `repo`, `user`, and `read:org`. So can you please update it in the GitHub documentation?

**Comment by leemthompo** [comment]
@parthpuri-elastic cool sounds good thanks for the ping!

**Comment by danajuratoni** [comment]
Closing as done
