### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1887]
### Problem Description
MongoDB was identified to lack SSL support.

### Acceptance criteria
- [x] add SSL support to MongoDB
- [ ] check if other connectors in the portfolio are missing SSL support and should support it

**Comment by wangch079** [comment]
Started discovery on SSL support on MongoDB:

1. We use [motor](https://motor.readthedocs.io/en/stable/index.html) to connect to a Mongo database
2. `motor` is very similar to [PyMongo](https://pymongo.readthedocs.io/en/stable/), and the difference is that motor is an asynchronous framework while `PyMongo` is synchronous. 
3. `motor` supports SSL in the same ways as [PyMongo](https://pymongo.readthedocs.io/en/stable/examples/tls.html), just pass `tls=True` to [AsyncIOMotorClient](https://motor.readthedocs.io/en/stable/api-asyncio/asyncio_motor_client.html#motor.motor_asyncio.AsyncIOMotorClient) (change should go [here](https://github.com/elastic/connectors/blob/7baa53991844f3cf43464e0e3f5908277a859b48/connectors/sources/mongo.py#L109)).
4. We should introduce a new RCF `Use SSL` for users to configure, and take this value in when constructing `AsyncIOMotorClient`
5. From the [doc](https://pymongo.readthedocs.io/en/4.6.0/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient):

>Note that the use of SRV URIs implicitly enables TLS support. Pass tls=false in the URI to override.

**Comment by parthpuri-elastic** [comment]
Weekly status update [17 Nov 2023 to 23 Nov 2023]

- Start Implementation of Mongo SSL
- Trying to configure mongo instance with ssl certificate

**Comment by parthpuri-elastic** [comment]
Weekly status update [24 Nov 2023 to 30 Nov 2023]

- Implementation is almost done and internal testing is ongoing
- we will raise PR soon

**Comment by parthpuri-elastic** [comment]
Weekly status update [1 Dec 2023 to 7 Dec 2023]

- [PR](https://github.com/elastic/connectors/pull/1937) for MongoDB SSL Implementation was merged
- Raised [PR](https://github.com/elastic/kibana/pull/172658) in Kibana for native MongoDB Connector

**Comment by parthpuri-elastic** [comment]
Hey @leemthompo, I have added a few parameters related to SSL in the MongoDB Connector. Can you please update it as below in the documentation?

`ssl_enabled`

Whether SSL verification will be enabled. Default value is False.

`ssl_ca`

Content of the root certificate from the Certificate Authority (if SSL is enabled). Example:
```
-----BEGIN CERTIFICATE-----
MIID+jCCAuKgAwIBAgIGAJJMzlxLMA0GCSqGSIb3DQEBCwUAMHoxCzAJBgNVBAYT
...
7RhLQyWn2u00L7/9Omw=
-----END CERTIFICATE-----
```

`tls_insecure`

Disables various certificate validations (if SSL is enabled). Set it to true to disable certificate validations. Default value is `False`

**Comment by leemthompo** [comment]
@wangch079 I see SSL is available for Mongo on **8.12.0**.

See [SSL enabled](https://github.com/elastic/connectors/blob/8.12/connectors/sources/mongo.py#L145) is available in 8.12, with PEM certificate option. This is currently undocumented, not sure what situation is?

**Comment by danajuratoni** [comment]
@leemthompo / @parthpuri-elastic  Is there any remaining work for this ticket or can we close it?

**Comment by leemthompo** [comment]
[Docs PR is in flight](https://github.com/elastic/enterprise-search-pubs/pull/4201), we just have the additional complication of bug that was highlighted re Atlas deployments in 8.12 not syncing without SSL enabled

**Comment by leemthompo** [comment]
@parthpuri-elastic yes that docs PR merged a couple weeks ago

**Comment by kajal-elastic** [comment]
@danajuratoni , We've checked other connectors but we weren't able to find any connector that needs SSL inclusion. Hence, Please mark this issue as completed.
