### ISSUE TITLE
Containers are only ARM64

### ISSUE THREAD

**Issue by johnwc** [elastic/connectors#1890]
Since 8.10, all containers in the docker repo are only ARM64. The last AMD64 release was 8.9.
https://www.docker.elastic.co/r/enterprise-search/elastic-connectors

**Comment by seanstory** [comment]
Hi @johnwc 

Thanks for the report. Looking into this, I can see how this is happening, as right now our release process is pretty manual, and looks like the architecture is dependent on whose laptop the release image gets built on. We have plans in the near term to make our release process more robust, but in the mean time, I suggest just building the image yourself from source.

**Comment by seanstory** [comment]
Thanks for flagging. Automation to help us be consistent about this is coming soon!

In the mean time, we made sure to push 8.12.1.0 an an `amd64` image: 
```
docker pull docker.elastic.co/enterprise-search/elastic-connectors:8.12.1.0
```

**Comment by markjhoy** [comment]
This issue was address with https://github.com/elastic/connectors/pull/2152 -- going to close this out, as the new release process should be arm64, amd64, and a multi-arch image
