### ISSUE TITLE
Connector failing to connect to ES

### ISSUE THREAD

**Issue by johnwc** [elastic/connectors#1891]
## Bug Description
Running the docker connector 8.9.2 container, connecting to 8.11 ES. We are seeing the below error from the connector, and the index in Kibana never shows the connector has connected.

```
[FMWK][07:34:56][INFO] Running connector service version 8.9.2.0
[FMWK][07:34:56][INFO] Loading config from /config/config.yml
[FMWK][07:34:56][INFO] Preflight checks...
[FMWK][07:34:56][INFO] Waiting for NodeConfig(scheme='https', host='elasticsearch-es-http', port=9200, path_prefix='', headers={}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={}) (so far: 0 secs)
[FMWK][07:34:56][INFO] Extraction service is not configured, skipping its preflight check.
[FMWK][07:34:56][WARNING] Attempt 1/10 failed. Retrying...
[FMWK][07:34:56][WARNING] Could not find index .elastic-connectors-sync-jobs
```

### To Reproduce
1. Deploy ES stack with ECK
2. In kibana, create a index using connector, generate api key and config for connector.
3. Deploy pod with connector image with config & CA cert from ES.
4. View logs of pod to see it has failed.

## Expected behavior
Connects to ES, ES shows connector connected.

## Environment
K8s 1.26 deployed on-prem with Rancher 2.7.8

**Comment by seanstory** [comment]
Hi @johnwc - I think you're hitting two issues here.
1. you should make sure the Major and Minor versions of Elasticsearch and Connectors match. Here, if you want to use 8.11.x Elasticsearch, you should be using 8.11.x.y connectors.
2. In 8.9, connectors need to be deployed with Enterprise Search, which in that release was helping to manage index creation/management/migration for connectors. So if you choose to use 8.9 Elasticsearch and 8.9 connectors, you also need to include 8.9 Enterprise Search in your deployment.

**Comment by johnwc** [comment]
Thank you @seanstory  We got it up and connecting now. We were using 8.9.2 because that was the only AMD64 docker image available. We built a new image using your docs for 8.11 and we are using that one now. That got it connected and running. The only major issue we are facing is trying to figure out where we are supposed to be putting these config settings for [sync rule](https://github.com/elastic/connectors/blob/main/docs/DEVELOPING.md#sync-rules). Nothing states what file these are supposed to go in.

**Comment by johnwc** [comment]
Never mind, we just figured it out, it is in Kibana within the indexes sync rules tab.

**Comment by seanstory** [comment]
Nice! Sounds like y'all are making rapid progress! Don't hesitate to hit us up in [our community slack](https://join.slack.com/t/elasticstack/shared_invite/zt-274yhqy0x-dPi2iGWVuEUiruCAT9to9w) or our [discuss forum](https://discuss.elastic.co/c/enterprise-search/84) if you run into any more questions!
