### ISSUE TITLE
Jira/Confluence Data Center support

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#1957]
Our [Jira connector](https://www.elastic.co/guide/en/enterprise-search/current/connectors-jira.html) and [Confluence](https://www.elastic.co/guide/en/enterprise-search/current/connectors-confluence.html) have been thoroughly tested for Jira Cloud and Server. As Server products are EOL in 2024, we should verify connector's compatibility with [Jira Data Center](https://www.atlassian.com/enterprise/data-center/jira) and Confluence Data Center.

### Acceptance criteria
compatibility of Jira & Confluence connector with Jira & Confluence Data Center
- connector configuration
- ingested objects
- advanced sync rules
- DLS support
- documentation

**Comment by danajuratoni** [comment]
@kajal-elastic As discussed today, let's 

- add the _Jira Data Center_ as an option for `Jira data source`  
   <img width="190" alt="image" src="https://github.com/elastic/connectors/assets/102797748/0133f06a-0ef9-46c3-bf70-a827e85e6637">

- update [compatibility doc](https://www.elastic.co/guide/en/enterprise-search/current/connectors-jira.html#connectors-jira-compatability)
- document the known limitation for DLS and link to the official Atlassian docs

**Comment by danajuratoni** [comment]
cc: @seanstory

**Comment by moxarth-elastic** [comment]
Updates - 18th January 2024

we will raise two separate PRs for data center compatibility. One for adding RCFs and another is for DLS support.
- We've started working on adding a new configuration field for Jira and Confluence Data Center in the connector.

**Comment by seanstory** [comment]
@danajuratoni before we approve adding RCFs for Data Center, I just want to triple-check that this is really something we want to do. As I'd explained in this [slack thread](https://elastic.slack.com/archives/C01795T48LQ/p1704485334910079), the license cost for Data Center is prohibitive. Which means that we will probably not have a way for our devs to test/troubleshoot any issues that come up. And we know that Atlassian has a history of making sudden and unexpected API changes. I do not feel great about just assuming that X Server APIs will remain 100% identical/compatible with X Data Center APIs as the Data Center products evolve. 

Have we considered instead taking a weaker position, and just _documenting_ that our tests have thus-far demonstrated that the X Server connectors are compatible with X Data Center? Maybe just adding that to the kibana tooltip instead of adding a new RCF?

**Comment by akanshi-elastic** [comment]
@danajuratoni I have started exploring confluence data center API for DLS part but it seems API's are available for datacenter but none of the endpoint is working as expected. So I have raised a support ticket in their community channel for further updates on this. you can also track it [here](https://community.atlassian.com/t5/Confluence-questions/API-for-fetch-user-and-permission-for-space-is-not-working/qaq-p/2599758?utm_source=dm&utm_medium=unpaid-social&utm_campaign=P:online*O:community*I:social_share*).

**Comment by akanshi-elastic** [comment]
As per the comment on [issue](https://community.atlassian.com/t5/Confluence-questions/API-for-fetch-user-and-permission-for-space-is-not-working/qaq-p/2599758#M291177). we don't have proper space permissions for fetching the data

**Comment by danajuratoni** [comment]
>As per the comment on [issue](https://community.atlassian.com/t5/Confluence-questions/API-for-fetch-user-and-permission-for-space-is-not-working/qaq-p/2599758#M291177).
I'm not sure I follow... the links / missing endpoints mentioned in the linked comment are for confluence server, not data center.

**Comment by moxarth-elastic** [comment]
@leemthompo  Some changes required for Jira documentation on top of this [comment](https://github.com/elastic/connectors/pull/2075#issuecomment-1903355959):

Compatibility:
 - Jira Cloud or Jira Server/Data Center versions 7 or later are compatible with Elastic connector frameworks.
 - **[REMOVE]** 
   Jira Data Center editions are not currently supported.

Configuration:
- **[UPDATE for use_document_level_security field]** 
  Toggle to enable [document level security (DLS)](https://www.elastic.co/guide/en/enterprise-search/current/dls.html). When enabled, full syncs will fetch access control lists for each document and store them in the _allow_access_control field. Access control syncs fetch users' access control lists and store them in a separate index.

Limitation:
- When the data_source is set to Jira Data Center / Server, the connector is able to fetch only 1000 users for Access Control sync due the [limitation of an API](https://auth0.com/docs/manage-users/user-search/retrieve-users-with-get-users-endpoint#limitations) is used.

**Comment by akanshi-elastic** [comment]
@leemthompo Some changes required in Confluence documentation:

Configuration:
- data_center_username
   Confluence Data Center username
- data_center_password
  Confluence Data Center password
- use_document_level_security
   Toggle to enable [document level security (DLS)](https://www.elastic.co/guide/en/enterprise-search/current/dls.html). When 
   enabled, full syncs will fetch access control lists for each document and store them in the _allow_access_control field. Access 
   control syncs fetch users' access control lists and store them in a separate index.

Limitation:
- For running Confluence DLS for datacenter/server, user needs to install `Extender for Confluence`.

Can you please make these changes in the documentation?

**Comment by leemthompo** [comment]
@akanshi-elastic previously DLS was only available for Jira/Confluence Cloud. To be clear is DLS now available for all 3 data_source types?

**Comment by akanshi-elastic** [comment]
Yes now it available for all 3

**Comment by danajuratoni** [comment]
@leemthompo Jira DLS is available for both Server and Data Center in 8.13. Confluence DLS for Server and Data Center will be available first in 8.13.1. 
Do you have the info needed for the required doc changes?
Thanks!

**Comment by danajuratoni** [comment]
@akanshi-elastic is there any impact to advanced sync rules for either Jira or Confluence from features introduced in this ticket?

**Comment by danajuratoni** [comment]
> > Confluence DLS for Server and Data Center will be available first in 8.13.1.
> 
> Correction, in 8.14.0. I believe we'd decided previously that since it was a net-new feature, it needed to be in a Minor release, rather than in a Patch.

@seanstory the comments [on this PR](https://github.com/elastic/connectors/pull/2165) mention 8.13.1, could you please check it merged to the right version then?

**Comment by seanstory** [comment]
The [backport PR for 8.13](https://github.com/elastic/connectors/pull/2241) was created from the PR you linked, but ended up being closed after we concluded in slack and on that PR that it should not go into 8.13 after all. See: https://github.com/elastic/connectors/pull/2241#issuecomment-1988577102

I'll add a comment to the parent PR too, just for our future selves.

**Comment by akanshi-elastic** [comment]
@danajuratoni Jira is working fine with sync rules but for confluence datacenter, we need to change approach of pagination. I'll fix it and raise PR by tommorow.
