### ISSUE TITLE
Native Jira connector with DLS enabled cannot run Access Control sync in Kibana

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#1962]
## Bug Description

When I run a connector client for Jira, I can enable DLS and then run an access control sync:

<img width="1101" alt="Screenshot 2023-12-04 at 12 25 13 PM" src="https://github.com/elastic/connectors/assets/5288246/6f60eb32-e341-479f-8cf5-461a0dfbfddd">

However, with a native connector for Jira, the option is not available:

<img width="1248" alt="Screenshot 2023-12-07 at 3 47 47 PM" src="https://github.com/elastic/connectors/assets/5288246/e6d34ac9-1168-4aca-a2b7-51d24713623b">

### To Reproduce
1. create an 8.11.1 cloud deployment
2. create a native jira connector
3. configure and enable dls
4. can't run access control sync

## Expected behavior
You should have the option to run access control syncs

## Environment
v8.11.1 (probably in 8.10.x too)

## Additional context
SDH: https://github.com/elastic/sdh-enterprise-search/issues/1215

**Comment by efegurkan** [comment]
Confluence and Kibana are fixed by this PR https://github.com/elastic/kibana/pull/172930
