### ISSUE TITLE
Unexpected keyword argument: message when failing a sync job

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#1969]
## Bug Description
When load testing connectors I've seen the following message in the logs:

```
[FMWK][14:07:28][ERROR] Failed to mark idle job #3lCESYwBsl1UQQ12BxQw as error: SyncJob.fail() got an unexpected keyword argument 'message'
```

Seems like there's an error in the code that handles job failure and some arguments are passed incorrectly

**Comment by seanstory** [comment]
Shoot this is probably my fault - I changed the param to `error`. Didn't realize it was a kwarg

**Comment by artem-shelkovnikov** [comment]
Ah it happens, the test that checked this functionality also failed to catch the issue 🗡️
