### ISSUE TITLE
[Google Drive] Unable to Retrieve File Permissions for Users with Read-Only Access

### ISSUE THREAD

**Issue by joemcelroy** [elastic/connectors#1979]
## Bug Description

This organisation has 2 files:

File 1: Owned by User A, and User C has read access.
File 2: Owned by User B
Fetch user -> [User A, User B, User C]
User A:
O Fetch files -> [File 1]
O Fetch file content and permissions: This works perfectly, as user A has write access.

User B: Also works perfectly.

User C
O Fetch files -> [File 1]
O Fetch file content and permissions: This throws an error (403, cannot fetch permissions)

### Expected behavior
The ideal state of Documents in Elasticsearch should have been:

File 1
O _allow_access_control: [User A, User C]
File 2
O _allow_access_control: [User B]

### Actual Behavior

File 1
O _allow_access_control: []
File 2
O _allow_access_control: [User B]

## Additional context
Version: 8.11.1

Jedr has advised to update the filters to `q="trashed=false and 'me' in writers"` to understand if it fixes the issue (link in SDH issue)

The customer has confirmed this works in linked SDH issue

**Comment by seanstory** [comment]
CC @jedrazb - can you add effort and priority labels as you understand them?

**Comment by jedrazb** [comment]
I will try to pick this up once I have some time. We already have a suggested fix, it's just a matter of manual testing to make sure we don't break something else accidentally.
