### ISSUE TITLE
[GitHub] Connector raises error in case of admin:org and write:org scopes

### ISSUE THREAD

**Issue by parth-elastic** [elastic/connectors#1983]
## Bug Description
After GitHub DLS connector only checks `repo`, `user` and `read:org` scopes in `_remote_validation` and raises a configuration error in the cases of `admin:org` and `write:org`.

## Expected behavior
The connector should run with `admin:org` and `write:org` scopes.

## Proposed Solution
Validate `admin:org` and `write:org` scopes in `_remote_validation`

**Comment by seanstory** [comment]
It might be worth logging a warning if we find these, as they are excessively privileged? We want to encourage users to use the least-privilege principal, but I agree that erroring is probably taking it too far.
