### ISSUE TITLE
[Teams] Unable to run Teams connector in 8.12.0

### ISSUE THREAD

**Issue by kajal-elastic** [elastic/connectors#1988]
## Bug Description
Unable to run Teams Connector in 8.12.0 (latest) Elastic deployment as the connector is stucked on log: Content sync job execution service started, listening to events from {elasticsearch url} 

### To Reproduce
1. Go to Indices -> Create a new Index -> Use a Connector
2. Click on teams and create a index by specifying a name
3. Deploy the connector by providing the elasticsearch credentials in config.yml 
4. Execute make run
5. Observe the logs displayed on console

## Expected behavior
Teams connector should pick up the configuration changes and connect to Elastic instance in order to run the connector

## Actual behavior
Sync gets stucked at - Content sync job execution service started, listening to events from {elasticsearch url}
Access control sync job execution service started, listening to events from {elasticsearch url}

## Environment
Elastic Deployment : 8.12.0(latest)
Branch : 8.12
connector version:  8.12.0.0

## Additional context
By default, service_type is displayed as teams on UI, whereas in the connectors->sources , it is microsoft_teams
So the service_type displayed on UI should be microsoft_teams in order to make it consistent and make the connector work

**Comment by kajal-elastic** [comment]
@DianaJourdan @danajuratoni When index is created using **Teams Connector Client** 
![teams-connector](https://github.com/elastic/connectors/assets/152139266/06abc45c-7b7d-4bd0-805d-66474d212f28)
Configuration contains service_type value as **teams** in UI : 
![teams-config](https://github.com/elastic/connectors/assets/152139266/c26d1cd6-1ec1-462b-bf15-433a69187df2)
If connector is Deployed using this configuration, Connector is stucked at log mentioned in issue.
But if the connector is executed as **customized connector** and **microsoft_teams** is mentioned as service_type 
![microsoft_teams](https://github.com/elastic/connectors/assets/152139266/3f9faf9e-1480-4c22-8a44-474eee4f7675)
Connector is executed successfully. 
So, It seems the issue is from the UI side and needs to be fixed from your end.

**Comment by danajuratoni** [comment]
@efegurkan can you please take a look an confirm whether Kibana uses service_type `teams` or `microsoft_teams` by default?

**Comment by danajuratoni** [comment]
Issue is present in 8.11 as well

**Comment by kajal-elastic** [comment]
@danajuratoni  For Teams, Currently we're facing the below errors with the credentials that were previously used for testing. 
1. An error is displayed indicating the requirement to use Multifactor Authentication. But in this case the MFA is already enabled for the configured user. 
![MFA error](https://github.com/elastic/connectors/assets/152139266/14eaba97-e590-4b78-a797-f93f7fde5bd5)

2. Another error faced is that the user or Administrator has not consented to use the application . But in this case the Admin consent for the permissions is already granted for the registered App in Azure . 
![authorizarion issue](https://github.com/elastic/connectors/assets/152139266/f82298d9-e26e-4204-bdab-7c83c32c3b82)

We're working on resolving the issues and will update if there are any changes . 
If there is any anything your team is aware of, Please let us know.

**Comment by efegurkan** [comment]
@danajuratoni in Kibana the `service_type` is `teams` as specified O am creating a PR to update the service type aimed for 8.12.1

**Comment by danajuratoni** [comment]
@kajal-elastic can you please confirm the "service_type" issue is resolved by @efegurkan's fix?

**Comment by danajuratoni** [comment]
> [below errors with the credentials that were previously used for testing](https://github.com/elastic/connectors/issues/1988#issuecomment-1873247349)

cc: @navarone-feekery in case this is a known issue

**Comment by kajal-elastic** [comment]
@danajuratoni  For the first issue , The error was faced as the account had MFA enabled and it is a known issue that connector doesn't work with MFA .
For the solution user needs to Perform this troubleshooting steps: https://github.com/elastic/enterprise-search-microsoft-teams-connector?tab=readme-ov-file#troubleshoot-access-token-generation 

For the second issue , It was resolved by granting admin consent to the organization on Microsoft Entra Admin Center  

![Grant Admin Consent for MSFT](https://github.com/elastic/connectors/assets/152139266/544ec00c-58d9-4c66-a4ed-0e590fc62414)

Currently, checking the Kibana fix, will update here once done.

**Comment by kajal-elastic** [comment]
@efegurkan @danajuratoni service_type issue is resolved now and I'm able to run the teams connector in 8.12

**Comment by bekhit** [comment]
> @danajuratoni For Teams, Currently we're facing the below errors with the credentials that were previously used for testing.
> 
> 1. An error is displayed indicating the requirement to use Multifactor Authentication. But in this case the MFA is already enabled for the configured user.
>    ![MFA error](https://private-user-images.githubusercontent.com/152139266/293573464-14eaba97-e590-4b78-a797-f93f7fde5bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjgyNzIsIm5iZiI6MTcwNDgyNzk3MiwicGF0aCI6Ii8xNTIxMzkyNjYvMjkzNTczNDY0LTE0ZWFiYTk3LWU1OTAtNGI3OC1hNzk3LWY5M2Y3ZmRlNWJkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxOTE5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDRhZTkyMDQ0N2U5ZmY5MDUwNTVhZDdjNTZlMjRiMDA4MzJlMDJlMGFlYzgzMDFhYWZhZTRiNjc3MzY2MDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6dT8ix1hq_nqBbwoLG2YxDF8G5rsAI6X5ZoM4yH8kTg)
> 2. Another error faced is that the user or Administrator has not consented to use the application . But in this case the Admin consent for the permissions is already granted for the registered App in Azure .
>    ![authorizarion issue](https://private-user-images.githubusercontent.com/152139266/293573463-f82298d9-e26e-4204-bdab-7c83c32c3b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjgyNzIsIm5iZiI6MTcwNDgyNzk3MiwicGF0aCI6Ii8xNTIxMzkyNjYvMjkzNTczNDYzLWY4MjI5OGQ5LWUyNmUtNDIwNC1iZGFiLTdjODNjMzJjM2I4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxOTE5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzY2N2U1ZDg5MzQ4ZDRjN2IyOTc1OWM2OTZjYjFjMTQ4MDgwM2Q4YTRlM2YxNmMwZDNlNGVjYjdkOWYyYWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OQ4OUQNwVPMrwn-CTC8mSEqYgjV5U23psVnmuOIBcNQ)
> 
> We're working on resolving the issues and will update if there are any changes . If there is any anything your team is aware of, Please let us know.

i am facing the same for error # 2 (Admin Consent) .. any update on that ?

**Comment by kajal-elastic** [comment]
@bekhit In order to resolve the issue, Below steps can be followed:
Go to https://entra.microsoft.com/ --> Login with Admin Credentials --> Click on `Applications` on the left hand side --> Enterprise Applications --> Click on your application from All applications --> Permissions --> Grant Admin consent. 

Refer the screenshot mentioned in the above [comment](https://github.com/elastic/connectors/issues/1988#issuecomment-1874923288)

**Comment by bekhit** [comment]
> ick on `Applications` on the left hand side -->

Hi Kajal,

Thank you for the reply.

In fact, we already granted the admin consent and followed the exact steps .. however, it keeps showing the same Interactive Permission request error as per the screenshot below 

![image](https://github.com/elastic/connectors/assets/30300500/c498e52d-f07e-4666-93ac-c1629eccae51)

**Comment by kajal-elastic** [comment]
It Seems like you're Granting Admin Consent from Azure Portal where the application was created. 
Can you check with Admin and Grant permission to Application on Microsoft Entra Admin Center ? as mentioned in steps above

Reference: https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/grant-admin-consent?pivots=portal#:~:text=To%20grant-,tenant%2Dwide%20admin%20consent,-to%20an%20app

**Comment by bekhit** [comment]
> It Seems like you're Granting Admin Consent from Azure Portal where the application was created. Can you check with Admin and Grant permission to Application on Microsoft Entra Admin Center ? as mentioned in steps above
> 
> Reference: https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/grant-admin-consent?pivots=portal#:~:text=To%20grant-,tenant%2Dwide%20admin%20consent,-to%20an%20app

We did the same .. but for the Return URL we just kept it to a public website and it is still giving the same error after I logged in using the Teams connector app user name. Again it says request admin consent!

**Comment by kajal-elastic** [comment]
@bekhit Can you please try by creating a New application in Azure Portal and providing the permissions and admin consent for the same?

**Comment by bekhit** [comment]
> @bekhit Can you please try by creating a New application in Azure Portal and providing the permissions and admin consent for the same?

@kajal-elastic  It is woking now after upgrading to the latest connector and Elasticsearch 8.12.0.

However, the User Graph API was failing.
Also where can I find he documentation that allows me to filter only specific data to be indexed? (ie. Only Documents in a specific Teams site)

**Comment by kajal-elastic** [comment]
@bekhit Advanced Sync rules are not supported for Teams connector yet.

**Comment by bekhit** [comment]
> @bekhit Advanced Sync rules are not supported for Teams connector yet.

              @bekhit Advanced Sync rules are not supported for Teams connector yet.

_Originally posted by @kajal-elastic in https://github.com/elastic/connectors/issues/1988#issuecomment-1905335360_

@kajal-elastic Update:

The Consent error is gone as described. However, we are getting a lot of unauthorized errors for events, channels, users, etc. as a warning from Graph API as per the screenshot below. I am getting some data for items and Unser Meetings .. nut after 2 Hours the Connector stuck with the message on screenshot 2 """Verify that the correct Graph API and Microsoft Teams permissions are granted to the app and admin consent is given. If the permissions and consent are correct, wait for several minutes and try again..""".

Also a lot of QueeMem error came before the connector stuck with the Authorization error (Screenshot below)

NOTE: the admin consent is granted on Azure App and I have reapplied again to be sure but still the Authorization error still came.


![image](https://user-images.githubusercontent.com/30300500/298853636-f3b10c83-290c-430c-ad76-6aea35c6c499.png)

![image](https://user-images.githubusercontent.com/30300500/298853947-95af18a8-c654-403d-afab-84a6a761f072.png)

              @bekhit Advanced Sync rules are not supported for Teams connector yet.

_Originally posted by @kajal-elastic in https://github.com/elastic/connectors/issues/1988#issuecomment-1905335360_

@kajal-elastic Update:

The Consent error is gone as described. However, we are getting a lot of unauthorized errors for events, channels, users, etc. as a warning from Graph API as per the screenshot below. I am getting some data for items and Unser Meetings .. nut after 2 Hours the Connector stuck with the message on screenshot 2 """Verify that the correct Graph API and Microsoft Teams permissions are granted to the app and admin consent is given. If the permissions and consent are correct, wait for several minutes and try again..""".

Also a lot of QueeMem error came before the connector stuck with the Authorization error (Screenshot below)

NOTE: the admin consent is granted on Azure App and I have reapplied again to be sure but still the Authorization error still came.


![image](https://user-images.githubusercontent.com/30300500/298853636-f3b10c83-290c-430c-ad76-6aea35c6c499.png)

![image](https://user-images.githubusercontent.com/30300500/298853947-95af18a8-c654-403d-afab-84a6a761f072.png)

![Screenshot 2024-01-23 003557](https://user-images.githubusercontent.com/30300500/298855977-82d36635-1b2d-4b39-93fa-e91cd265aad4.png)

**Comment by akanshi-elastic** [comment]
Hi @bekhit Can you please share the screenshot of all added permissions once again? I just need to verify the issue

**Comment by bekhit** [comment]
> Hi @bekhit Can you please share the screenshot of all added permissions once again? I just need to verify the issue

Hi @akanshi-elastic .. permission is there asper the Connector documentation and rechecked.

![image](https://github.com/elastic/connectors/assets/30300500/0c216ffb-77f7-408f-84dc-e55af9927b83)

**Comment by kajal-elastic** [comment]
@bekhit Authorization issue is faced as some of the permissions doesn't have Admin Consent (As per the Screenshot shared).
Can you please grant Admin Consent for all the permissions ? by clicking on Grant Admin Consent for Abu Dhabi Executive Office

**Comment by bekhit** [comment]
> Can you please grant Admin Consent for all the permissions ? by clicking on Grant Admin Consent for Abu Dhabi Executive Office

Hi @kajal-elastic this column is actually about Teams "Require admin consent" flag .. not the exact "admin consent".
Below is another screenshot indicating we have given the required admin consent.

![image](https://github.com/elastic/connectors/assets/30300500/38c05530-68fd-4111-844c-1d4ae06e1c62)
