### ISSUE TITLE
[SQL] Join queries can fail if column PK names are the same across tables

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#2002]
## Bug Description
- Reported in MSSQL by [a discuss user](https://discuss.elastic.co/t/search-connectors-microsoft-sql/346263)
- Reported in Postgres by @poremland 

An advanced sync rules query like:
```
SELECT TOP 10 Bird.Name, Chicken.Food FROM Bird INNER JOIN Chicken ON Chicken.TagId = Bird.Id;
```
Should work, and we expect Joins to be one of the most common use cases for Advanced Sync Rules on SQL connectors. However, this type of Advanced Sync Rule leads to warnings in the logs like:
```
[FMWK][06:31:05][WARNING] [Connector id: u****************L, index name: search-m********, Sync job id: **************] Skipping custom query for tables Bird, Chicken as there are multiple tables with same primary key column name.
```

Blocks like 
https://github.com/elastic/connectors/blob/664777162b66f9a0ac0c2037f96d717c5303d6f9/connectors/sources/mysql.py#L564-L568

are in all our SQL connectors, but it's unclear to me what the purpose is, and why we're checking uniqueness for table PKs.

Both Paul and the discuss user have validated that using `AS` in the query to rename selected fields does not help.

### To Reproduce
1. create a SQL db with two tables that both have a PK on an `ID` column
2. create a connector for that database
3. setup advanced sync rules to join your two tables on `ID`
4. note that your sync results in no data

## Expected behavior
You should be able to use advanced sync rules for joins, even if the PK columns have the same name.

## Environment
8.11-8.13

## Additional context
Slack thread: https://elastic.slack.com/archives/C01795T48LQ/p1702570480692019

**Comment by seanstory** [comment]
Related issue: https://github.com/elastic/connectors/issues/467

**Comment by seanstory** [comment]
@timgrein is this still on your radar? Looks like MSSQL and Oracle are still incomplete?

**Comment by timgrein** [comment]
MSSQL fix: https://github.com/elastic/connectors/pull/2209

**Comment by timgrein** [comment]
Closing as all PRs for PostgreSQL, MySQL and MSSQL were merged
