### ISSUE TITLE
[Confluence] Add field `emailAddress` field in Access Control index

### ISSUE THREAD

**Issue by praveen-elastic** [elastic/connectors#2026]
### Problem Description

Based on our [code](https://github.com/elastic/connectors/blob/main/connectors/sources/atlassian.py#L143-L150), only identity.account_id and identity.display_name fields are defined to be output. This confirm current code does not emit the email address to output Elasticsearch index.

>         user_document = {
>             "_id": account_id,
>             "identity": {
>                 "account_id": prefixed_account_id,
>                 "display_name": prefixed_account_name,
>             },
>             "created_at": iso_utc(),
>         }

Field email is not present.

### Proposed Solution

 Add field `identity.email_address`, ~`identity.timezone`~ and `identity.locale` from above use case to be output to Elasticsearch index.

**Comment by danajuratoni** [comment]
@praveen-elastic Please add fields identity.timezone and identity.locale as well as they should be available in the returned user object. (added them to the ticket above)

**Comment by praveen-elastic** [comment]
Progress Summary: I've raised a PR for adding new fields: `email-address` and `locale`.

**Comment by praveen-elastic** [comment]
Update: PR is ready for review. `timezone` is no longer being considered due to unavailability in the API response. So `email-address` and `locale` are added
