### ISSUE TITLE
[Network Drive] Connector barely produces any logs

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#2120]
## Bug Description
Connector barely produces any info/debug logs - it's impossible to understand what's going on during sync.

### To Reproduce
1. Run a functional test for network drive connector with `make ftest NAME=network_drive`
2. Observe logs
3. There are barely any logs

## Expected behavior
Connector has to produce info/debug logs that explain what is happening during sync

**Comment by praveen-elastic** [comment]
@artem-shelkovnikov Can you please let me know which kind of info, debug logs you want ? The smb library is itself silent.
Do you prefer to add logs like these: https://github.com/elastic/connectors/pull/1953 ?

**Comment by artem-shelkovnikov** [comment]
We should have DEBUG logs that indicate what's going on. So before every call to SMB there needs to be a log about what we're fetching. If something goes wrong, we need a log about what and why.

Example log lines:
```
Fetching the directory tree from remote server
Fetching content of directory "documents"
Fetching content of directory "documents/sales"
Fetching content of file "documents/sales/report-q4-2022.xls"
```

Hope it helps.
