### ISSUE TITLE
[Network Drive] Connector does not work with SMB server on non-default ports

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#2124]
## Bug Description
It's impossible to make Network Drive sync data from non-default port SMB server.

### To Reproduce
1. Run SMB server on non-default port (for example, on port 1234)
2. Set up a network drive connector to connect to this SMB server and sync data from
3. Run sync

## Expected behavior
Sync should finish successfull

## Additional context
This ticket should be specifically tested on a real Windows Server instance.

**Comment by praveen-elastic** [comment]
I have asked IT team to configure a Windows Network Drive with non-default port, so that i can implement a fix for this.
