### ISSUE TITLE
[MongoDB] Validation incorrectly reports warnings about access against Atlas

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#2135]
## Bug Description
MongoDB connector running against Atlas instance reports warnings that collection is not accessible, which is not true.

See example log line:

```
[FMWK][12:35:20][WARNING] [Connector id: KE4kVY0BJIBs1DUKlXgy, index name: search-mongodb] Unable to access 'sample_geospatial.shipwrecks' as user 'elastic'
```

This message is misleading - access is possible, it's just our validation calls `validate` method that is not available to users of MongoDB Atlas.

### To Reproduce
1. Set up a MongoDB connector against an Atlas instance we have in Vault credentials for
2. Run a sync
3. See logs - warning is reported that there's no access to collection, but a sync is able to run and sync documents

## Expected behavior
Warning should not be shown

**Comment by artem-shelkovnikov** [comment]
Problem is in different permissions that users in Atlas have vs ones that users in standalone MongoDB can have.

**Comment by seanstory** [comment]
Didn't realize we had an issue for this. I fixed this in https://github.com/elastic/connectors/pull/2249
