### ISSUE TITLE
[MongoDB] 8.12 Docker builds fail due to bumped Python version

### ISSUE THREAD

**Issue by trunglh88** [elastic/connectors#2144]
### To Reproduce
1. Setup ElasticSearch, kibana, Elastic Connectors using docker-compose.yml
2. run docker compose up -d
3. Elastic Connector show error

## Expected behavior
elastic-connectors-1  | [FMWK][12:41:51][INFO] Running connector service version 8.12.1.0
elastic-connectors-1  | [FMWK][12:41:51][INFO] Loading config from /config/config.yml
elastic-connectors-1  | [FMWK][12:41:51][INFO] Running preflight checks
elastic-connectors-1  | [FMWK][12:41:51][INFO] Waiting for NodeConfig(scheme='https', host='es01', port=9200, path_prefix='', headers={}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={}) (so far: 0 secs)
elastic-connectors-1  | [FMWK][12:41:51][INFO] Extraction service is not configured, skipping its preflight check.
elastic-connectors-1  | [FMWK][12:41:51][INFO] Job Scheduling Service started, listening to events from https://es01:9200
elastic-connectors-1  | [FMWK][12:41:51][INFO] Content sync job execution service started, listening to events from https://es01:9200
elastic-connectors-1  | [FMWK][12:41:51][INFO] Access control sync job execution service started, listening to events from https://es01:9200
elastic-connectors-1  | [FMWK][12:41:52][CRITICAL] [Connector id: 230umI0BwJlFGgNaeZIS, index name: search-manga] cannot import name 'coroutine' from 'asyncio' (/usr/local/lib/python3.11/asyncio/__init__.py)
elastic-connectors-1  | Traceback (most recent call last):
elastic-connectors-1  |   File "/app/connectors/protocol/connectors.py", line 782, in prepare
elastic-connectors-1  |     source_klass = get_source_klass(fqn)
elastic-connectors-1  |                    ^^^^^^^^^^^^^^^^^^^^^
elastic-connectors-1  |   File "/app/connectors/source.py", line 851, in get_source_klass
elastic-connectors-1  |     module = importlib.import_module(module_name)
elastic-connectors-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
elastic-connectors-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
elastic-connectors-1  |     return _bootstrap._gcd_import(name[level:], package, level)
elastic-connectors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
elastic-connectors-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
elastic-connectors-1  |   File "/app/connectors/sources/mongo.py", line 16, in <module>
elastic-connectors-1  |     from motor.motor_asyncio import AsyncIOMotorClient
elastic-connectors-1  |   File "/app/lib/python3.11/site-packages/motor/motor_asyncio.py", line 18, in <module>
elastic-connectors-1  |     from .frameworks import asyncio as asyncio_framework
elastic-connectors-1  |   File "/app/lib/python3.11/site-packages/motor/frameworks/asyncio/__init__.py", line 27, in <module>
elastic-connectors-1  |     from asyncio import coroutine  # noqa: F401 - For framework interface.
elastic-connectors-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
elastic-connectors-1  | ImportError: cannot import name 'coroutine' from 'asyncio' (/usr/local/lib/python3.11/asyncio/__init__.py)
elastic-connectors-1  | [FMWK][12:41:52][CRITICAL] [Connector id: 230umI0BwJlFGgNaeZIS, index name: search-manga] Could not instantiate connectors.sources.mongo:MongoDataSource for mongodb
elastic-connectors-1  | Traceback (most recent call last):
elastic-connectors-1  |   File "/app/connectors/protocol/connectors.py", line 782, in prepare
elastic-connectors-1  |     source_klass = get_source_klass(fqn)
elastic-connectors-1  |                    ^^^^^^^^^^^^^^^^^^^^^
elastic-connectors-1  |   File "/app/connectors/source.py", line 851, in get_source_klass
elastic-connectors-1  |     module = importlib.import_module(module_name)
elastic-connectors-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
elastic-connectors-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
elastic-connectors-1  |     return _bootstrap._gcd_import(name[level:], package, level)
elastic-connectors-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
elastic-connectors-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
elastic-connectors-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
elastic-connectors-1  |   File "/app/connectors/sources/mongo.py", line 16, in <module>
elastic-connectors-1  |     from motor.motor_asyncio import AsyncIOMotorClient
elastic-connectors-1  |   File "/app/lib/python3.11/site-packages/motor/motor_asyncio.py", line 18, in <module>
elastic-connectors-1  |     from .frameworks import asyncio as asyncio_framework
elastic-connectors-1  |   File "/app/lib/python3.11/site-packages/motor/frameworks/asyncio/__init__.py", line 27, in <module>
elastic-connectors-1  |     from asyncio import coroutine  # noqa: F401 - For framework interface.
elastic-connectors-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
elastic-connectors-1  | ImportError: cannot import name 'coroutine' from 'asyncio' (/usr/local/lib/python3.11/asyncio/__init__.py)

Error show in Kibana
![image](https://github.com/elastic/connectors/assets/5045717/59855864-449d-4205-a445-ed9b8204f191)

- OS: ubuntu 22.04
- Version 8.12.1

**Comment by navarone-feekery** [comment]
@trunglh88 thanks for submitting an issue!

I saw that you also posted on the Elasticsearch forums [here](https://discuss.elastic.co/t/elastic-connectors-has-error-cannot-import-name-coroutine-from-asyncio/353019). I can see in your config file that you have specified the `source`. By default, all sources are already included so there's no need to specify the source unless you're developing a new source. (The one [here](https://github.com/elastic/connectors/blob/a62364daadf74811e663f27d16c81ce3190ade7a/config.yml#L204-L212) is only an example and shouldn't typically be available).

Can you try removing the following from your config.yml?

```
sources:
  mongodb: connectors.sources.mongo:MongoDataSource
```

**Comment by navarone-feekery** [comment]
The change was reverted, so docker images now run on python v3.10 again. I've confirmed that the v8.12.1.1 docker image can build and syncs data without issue.

Thanks again for bringing this to our attention!
