### ISSUE TITLE
Count of documents shown in connector overview page is twice the number of actual documents indexed on 8.13.0 elastic deployment

### ISSUE THREAD

**Issue by kajal-elastic** [elastic/connectors#2203]
## Bug Description
Count of documents displayed in connector index is twice the number of actual documents indexed and present in source on 8.13.0 elastic deployment

### To Reproduce

1. Go to connectors and create a native connector 
2. Attach an index to the connector
3. Enter Configuration values for the connector and refresh the page
4. Run Full sync by Clicking on Sync -> Full Sync
5. Go to Overview page and check the documents indexed in Connector

## Expected behavior
Count of documents shown in connector overview page and actual documents indexed should be same

## Screenshots
![doc-count](https://github.com/elastic/connectors/assets/152139266/c7425b4d-3b00-4ee4-86f4-5b44e2c11763)

## Environment
Elastic Deployment : 8.13.0(latest)

## Additional context
This was tested on 8.13.0 elastic deployment BC1

**Comment by efegurkan** [comment]
Hey this is a FE bug 99%, 

I am checking for a solution, in the meantime, @kajal-elastic can you confirm if you go to `indices -> search-gcs` index to confirm you see the correct amount of docs.

**Comment by kajal-elastic** [comment]
@efegurkan The correct number of documents is 8 documents. However , on UI it was getting displayed as 16 documents
