### ISSUE TITLE
Elasticsearch Connector API rejects valid array in filtering pptions with `x_content_parse_exception`

### ISSUE THREAD

**Issue by chantzlarge** [elastic/connectors#2212]
## Bug Description

When attempting to update connector filtering options via the Elasticsearch Connector API using a `curl` command, the API returns an unexpected parsing error. The error suggests that the `connector_filtering_advanced_snippet` value does not support values of type START_ARRAY, which contradicts the expected input format for filtering options.

### To Reproduce

1\. Execute the following `curl` command:

```
curl \
        -s \
        -X PUT \
        --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt \
        -u ${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD} \
        -H 'Content-Type: application/json' \
        -d '{"filtering":[{"active":{"advanced_snippet":{"value":[{"tables":["search_indices"],"query":"SELECT * FROM search_indices"}]},"rules":[{"field":"_","rule":"regex","id":"DEFAULT","value":".*","order":0,"policy":"include"}],"validation":{"errors":[],"state":"valid"}},"domain":"DEFAULT"}]}' \
        https://elasticsearch:9200/_connector/marketplace/_filtering
```

2\. Observe the parsing error in the response.

## Expected behavior

The expected behavior is for the connector filtering rules to be updated without any errors, accepting the JSON array format for the `advanced_snippet` value as per documentation or previous version compatibility.

## Screenshots

N/A

## Environment

- OS: Linux (exact version not specified)
- Browser: N/A (using `curl` command-line tool)
- Version: 8.12.1

## Additional context

This issue seems related to a previously reported issue on GitHub: https://github.com/elastic/connectors/issues/2189#event-11859589526. It suggests there may be a regression or a change in the expected format for filtering rules in the Elasticsearch Connector API. Further investigation into the API documentation and recent changes may be required to understand the discrepancy and resolve the parsing error.

The error message from the API:
```
{
    "error": {
        "root_cause": [
            {
                "type": "x_content_parse_exception",
                "reason": "[1:54] [connector_filtering_advanced_snippet] value doesn't support values of type: START_ARRAY"
            }
        ],
        "type": "x_content_parse_exception",
        "reason": "[1:54] [connector_update_filtering_request] failed to parse field [filtering]",
        "caused_by": {
            "type": "x_content_parse_exception",
            "reason": "[1:54] [connector_filtering] failed to parse field [active]",
            "caused_by": {
                "type": "x_content_parse_exception",
                "reason": "[1:54] [connector_filtering_rules] failed to parse field [advanced_snippet]",
                "caused_by": {
                    "type": "x_content_parse_exception",
                    "reason": "[1:54] [connector_filtering_advanced_snippet] value doesn't support values of type: START_ARRAY"
                }
            }
        }
    },
    "status": 400
}
```

**Comment by jedrazb** [comment]
Hey @chantzlarge thank you for reporting! If I understand correctly, the issue you describing is the same as in #2189 right? In that case https://github.com/elastic/elasticsearch/pull/105633 should indeed fix the issue in the next release.
