### ISSUE TITLE
SharePoint Server connector doesn't support Host Named Site Collections and NTLM authentication

### ISSUE THREAD

**Issue by anghelnicolae** [elastic/connectors#2340]
### Problem Description

The "Site Collections" field should contain the full URLs of the site collections to be indexed, instead of just the suffix of a host header site collection. It should also only use NTLM authentication since Basic authentication is not secure and not recommended by Microsoft.

**Comment by seanstory** [comment]
Hi @anghelnicolae - sounds like you're asking for two separate enhancements here. Can I ask you to file them separately, one for full URLs in the Site Collections field, and a separate issue for NTLM support?

In each, it would be helpful if you can share more about your use case. Why the current features aren't sufficient, what your proposal is and why it would work better for you and for other use cases, if there are any alternatives, etc.

**Comment by anghelnicolae** [comment]
Hi @seanstory 
The only reason I created this is because the pull request description said I should. I haven't done pull requests on Github before so please excuse me if I misunderstood anything. I plan to add a lot of improvements to the SharePoint Server connector, this was just a small step in that direction.
