### ISSUE TITLE
Synchronizing content from Jira Data Center is only supported if Jira is accessible on the root path

### ISSUE THREAD

**Issue by dodie** [elastic/connectors#2343]
### Problem Description
Connecting to a Jira Data Center is only successful if Jira is accessible on the root path, e.g., https://exampledomain/. If my Jira instance is exposed on a different path, such as https://exampledomain/jira/, even if the "Jira host url" is set to this value the connector attempts to connect via https://exampledomain/, resulting in failure.

### Proposed Solution
The URLs used in the Jira connector are currently all absolute URLs, as seen in [jira.py#L61-L75](https://github.com/elastic/connectors/blob/34df05922fc2c0554ed2b45972289d52e13bde64/connectors/sources/jira.py#L61-L75). Inspired by the approach taken in the Confluence Connector ([confluence.py#56-65](https://github.com/elastic/connectors/blob/34df05922fc2c0554ed2b45972289d52e13bde64/connectors/sources/confluence.py#L56-L65)), I suggest removing the starting / from each URL to make them relative. This modification allowed me to synchronize data successfully from a Jira instance that is accessible on a custom path.

**Comment by seanstory** [comment]
Thanks for reporting! Makes sense, we'll take a look. 👀

**Comment by seanstory** [comment]
Our team has a PR up that should address this issue ☝️ 

Feel free to try it out, and/or provide feedback.

**Comment by dodie** [comment]
Looks good, thank you for the quick fix!
