### ISSUE TITLE
Synchronization job from Confluence never finishes if getting the attachment list fails

### ISSUE THREAD

**Issue by dodie** [elastic/connectors#2353]
## Bug Description
Normally when I start a sync job from Confluence, it synchronizes all contents correctly, and the status of the synchronization job is "Sync complete" as expected.
However, if [fetch_attachments](https://github.com/elastic/connectors/blob/4047c2c6edf97ae8cfc9c846b3ec62e0c4f88157/connectors/sources/confluence.py#L805) fails, then the corresponding `END_SIGNAL` is never put into the `queue` in [_attachment_coro](https://github.com/elastic/connectors/blob/4047c2c6edf97ae8cfc9c846b3ec62e0c4f88157/connectors/sources/confluence.py#L937). 
As a consequence, the `fetcher_count` will never reach 0 and the sync job will remain in the status of "Sync in progress" forever, even after synchronizing all contents.

In my case the source of the problem was that a page had an invalid attachment that was without a creation date, so this line failed:
https://github.com/elastic/connectors/blob/4047c2c6edf97ae8cfc9c846b3ec62e0c4f88157/connectors/sources/confluence.py#L837

And this appeared in the connector logs:
```
[FMWK][08:55:09][ERROR] Exception found for task Task-47119: 'when'
NoneType: None
```

Even if this is a data issue on the source system side, I think in this case the error should be handled more gracefully.

### To Reproduce
1. Set up a connector to Confluence Data Center.
2. Make sure the attachment list can't be obtained correctly. To simulate this, maybe the easiest way is to restrict the connector from accessing the `ATTACHMENT` endpoint. Alternatively, temporarily modify [fetch_attachments](https://github.com/elastic/connectors/blob/4047c2c6edf97ae8cfc9c846b3ec62e0c4f88157/connectors/sources/confluence.py#L837) to fail when processing the results for a given page. 
3. Start a full synchronization.
4. Wait, and observe that "Docs added" counter increases.
5. After a while, the "Docs added" counter increases no more as all content is synchronized, there are no errors visible in the last lines of the connector log, but the Status of the sync job remains "Sync in progress".

## Expected behavior
After all contents are synchronized, the Status of the synchronization job should be "Sync complete". The fact that the attachment endpoint could not be reached or that it returned faulty content should be visible in the logs.

## Environment
- OS: RHEL8, connector is run in a Docker container
- Connector Framework: enterprise-search/elastic-connectors:0.0.0.x (created at 2024-02-16)
  - *Edit: As discussed in the comments below, the problem can be experienced with the connector image 8.11.3.0 as well, tested against the stack version 8.11.4.*

## Additional context
As a workaround, I've modified [_attachment_coro](https://github.com/elastic/connectors/blob/4047c2c6edf97ae8cfc9c846b3ec62e0c4f88157/connectors/sources/confluence.py#L937) to guard the query parts with a try ... except to make sure that the last line is always executed and `END_SIGNAL` is queued. With this change the synchronization job finished with a "Sync complete" state.

**Comment by seanstory** [comment]
Thanks for filing, @dodie !

What version or branch of connectors are you using? We _should_ have something that is checking on running jobs periodically, and if they haven't had a heartbeat in a while (updating `last_seen`), they should be switched to a failure state. So I want to make sure this isn't actually 2 bugs, one with bad handling of attachment errors and one where our hung-jobs logic isn't working.

**Comment by artem-shelkovnikov** [comment]
Additionally, can you also include the version of the stack that you're using?

**Comment by seanstory** [comment]
Heh, we created the `0.0.0.x` when testing a new release mechanism. Thought, "if it's all 0's surely no one will use it" 😭 Didn't think about how someone might sort by date.

There's nothing _wrong_ with that image, but it would be better to move to one of our 8.11 releases if you're on 8.11 for the stack. That'll make supporting you easier/less confusing for any future issues you might file. :) 

Sounds like something's wrong with the heartbeat. Probably that we're still updating `last_seen`, just from a different thread than where the error occurred.

**Comment by dodie** [comment]
> we created the 0.0.0.x when testing a new release mechanism

I thought the intention is similar to `latest`, e.g. to contain the latest and greatest from the `main` branch. 😄 
I switched to this version from `8.11.x` because that did not have the incremental sync feature (at that time at least), something I also wanted to test.

Is it mandatory / recommended to use the same version as the stack version? The code itself (at least the Jira/Confluence connectors) look fairly version-agnostic.

Shall I retest the error handling / runaway sync issue with the `8.11.x` version? Based on the source code of the connector, I think it is affected by the "infinite 'Sync in progress'" problem regardless of the stack version we use.

**Comment by seanstory** [comment]
> Is it mandatory / recommended to use the same version as the stack version? 

Using a major/minor version that isn't aligned is not supported. Will things often work anyways? Yes. But when things _don't_ work, it's hard to know exactly what the issue is if we can't assume that Elasticsearch has defined the right index mappings, and Kibana is setting the right flags, and that the Elasticsearch APIs the connectors try to use _actually exist_ in the Elasticsearch its hitting. :) 

> Based on the source code of the connector

The source code of the connector isn't what should help terminate the hung job - that code lives in the "framework."

> Shall I retest the error handling / runaway sync issue with the 8.11.x version?

It would be excellent if you could. If not, we'll eventually get to it and try to reproduce.

**Comment by dodie** [comment]
>> Shall I retest the error handling / runaway sync issue with the 8.11.x version?
> 
> It would be excellent if you could. If not, we'll eventually get to it and try to reproduce.

I can now also confirm that the problem can be observed with stack version `8.11.4` and the connector image `8.11.3.0`.

**Comment by seanstory** [comment]
Thanks! Our team has drafted a fix ☝️ 
Feel free to try it out and/or provide feedback on the PR.
