### ISSUE TITLE
JIRA Connector cannot connect to JIRA if host name has a path

### ISSUE THREAD

**Issue by Gleb-Gadyatskiy** [elastic/connectors#2366]
## Bug Description
If JIRA is running as non-root web application (like https://jira.company.com/jira/), JIRA connector fails to communicate with it because it expects only Host name without path.

### To Reproduce
1. Create JIRA Connector and set Host = https://jira.company.com/jira/
2. Start Sync
3. Sync fails with 404 error, hitting https://jira.company.com 

## Expected behavior
JIRA Connector is able to work when JIRA host has Path, not only Host name.

## Proposed fix
https://github.com/elastic/connectors/pull/2365

**Comment by moxarth-elastic** [comment]
FYI @Gleb-Gadyatskiy , the same issue has already filed - https://github.com/elastic/connectors/issues/2343.
