### ISSUE TITLE
Synchronize the titles of ancestor pages for Confluence Pages

### ISSUE THREAD

**Issue by dodie** [elastic/connectors#2378]
### Problem Description
While searching for content in Confluence, it can be relevant to know the ancestor pages for a given page as pages can be deeply nested. For example, this might be useful to simply display this information on a search result page, but in some cases it can also be handy for searching (e.g. match documents based on the titles of the parent pages, or boost them if they have less parents).

### Proposed Solution
According to the [How to get parent page id in confluence rest api](https://community.atlassian.com/t5/Confluence-questions/How-to-get-parent-page-id-in-confluence-rest-api/qaq-p/2011416) forum entry, it is possible to get the ancestors via the following endpoint:

> <Confluence_Base_URL>/rest/api/content/<pageID>?expand=ancestors

The tradeoff is potentially a longer synchronization time as it needs an extra query, unless `expand=ancestors` can also work with the currently used `/rest/api/content/search` endpoint.

### Alternatives
The older [Workplace Search](https://www.elastic.co/guide/en/enterprise-search/current/docker.html) connector synchronizes the titles of the ancestor pages the `description` field in a format of "Parent Title 1/Parent Title 2".

**Comment by seanstory** [comment]
Thanks for filing, @dodie !

Can you elaborate some on the use case you have? I want to try to suss out if we'd have any particular requirements on how the ancestors would need to be stored/organized/indexed in order to meet your needs. For example, just displaying them has no requirements other than retrieving them, but searching for "Pages with ancestor A but NOT ancestor B" would probably require each ancestor being a distinct value, and not one concatenated string/description.

Also curious what your thoughts are on if this would be a feature that all users would always want. Perhaps this could be an optional toggle at connector setup time of "Fetch Ancestors?" to allow users to choose if the performance cost is something they're willing to pay.

**Comment by dodie** [comment]
Thanks for considering my feature request @seanstory!

> Can you elaborate some on the use case you have? I want to try to suss out if we'd have any particular requirements on how the ancestors would need to be stored/organized/indexed in order to meet your needs. For example, just displaying them has no requirements other than retrieving them, but searching for "Pages with ancestor A but NOT ancestor B" would probably require each ancestor being a distinct value, and not one concatenated string/description.

I think it would definitely be better if the parent pages are accessible as distinct ordered values than in a concatenated string.

Regarding the use-cases I we bumped into the following:

- Display the parents of a page in the search list.
- Match the query on the parent pages. E.g. if we have a page "MyProject" with a subpage "Getting Started", searching on both the title of the page and the ancestor titles would make a higher score for the query "MyProject Getting Started", which seems natural for users to search for.
- Boost documents that have fewer ancestors. The assumption is that most important content is usually not buried in a deeply nested structure.

**Comment by akanshi-elastic** [comment]
@dodie @seanstory  Do you want me to add ancestors in `title` field which is currently storing the page name only or it will be a separate field? Also Do you wnat to bifurcate ancestors name with spaces? If so then suppose page name is `Composed Looks` and subpage name is  `Demo subpage` then it will be like `Composed Looks Demo subpage`. Is it fine for you? Or instead of space we can bifurcate with hyphen or any other special character as well

**Comment by dodie** [comment]
From my point of view a separate field would be the best that would store multiple values, and the individual titles of the ancestor pages could be accessed individually. From the data point of view, this seems the cleanest option as from this structure it is quite easy to transform the data to any other structure without parsing the contents.

If this is not possible, or have downsides, I think a separate single text field could also do, e.g. where the titles of the ancestors are separated by a special delimiter character such as `/`. The downside of this solution is that this single text field needs to be parsed to get back the original chain of ancestors (e.g. split by `/`), so if a page title contains this character, it might break this logic.

**Comment by seanstory** [comment]
@akanshi-elastic how are the ancestors returned when `?expand=ancestors` is included? If possible, I'd like to keep our output documents as close to the output structure of the source API as possible. But I'd agree with @dodie 's intuitions and requests above - I'm just hoping those needs are already met in the output structure of confluence's API.

**Comment by akanshi-elastic** [comment]
@seanstory @dodie this is how API response looks like for page/blogpost:
```
{
            "id": "983041",
            "type": "page",
            "status": "current",
            "title": "page 3",
            "space": {
                "id": 360451,
                "key": "space1",
                "name": "space1",
                "description": {
                    "_expandable": {
                        "view": "",
                        "plain": ""
                    }
                },
                "type": "global",
                "status": "current",
                "_expandable": {
                    "settings": "/rest/api/space/space1/settings",
                    "metadata": "",
                    "operations": "",
                    "lookAndFeel": "/rest/api/settings/lookandfeel?spaceKey=space1",
                    "identifiers": "",
                    "permissions": "",
                    "icon": "",
                    "theme": "/rest/api/space/space1/theme",
                    "history": "",
                    "homepage": "/rest/api/content/360657"
                },
                "_links": {
                    "webui": "/spaces/space1",
                    "self": "https://crestdatasys-team-o5vdd7bm.atlassian.net/wiki/rest/api/space/space1"
                }
            },
            "ancestors": [
                {
                    "id": "360657",
                    "type": "page",
                    "status": "current",
                    "title": "space1 Home",
                    "macroRenderedOutput": {},
                    "extensions": {
                        "position": 535
                    },
                    "_expandable": {
                        "container": "/rest/api/space/space1",
                        "metadata": "",
                        "restrictions": "/rest/api/content/360657/restriction/byOperation",
                        "history": "/rest/api/content/360657/history",
                        "body": "",
                        "version": "",
                        "descendants": "/rest/api/content/360657/descendant",
                        "space": "/rest/api/space/space1",
                        "childTypes": "",
                        "schedulePublishInfo": "",
                        "operations": "",
                        "schedulePublishDate": "",
                        "children": "/rest/api/content/360657/child",
                        "ancestors": ""
                    },
                    "_links": {
                        "self": "https://crestdatasys-team-o5vdd7bm.atlassian.net/wiki/rest/api/content/360657",
                        "tinyui": "/x/0YAF",
                        "editui": "/pages/resumedraft.action?draftId=360657",
                        "webui": "/spaces/space1/overview"
                    }
                }
            ],
            "macroRenderedOutput": {},
            "extensions": {
                "position": 7
            },
            "_expandable": {
                "childTypes": "",
                "container": "/rest/api/space/space1",
                "schedulePublishInfo": "",
                "metadata": "",
                "operations": "",
                "schedulePublishDate": "",
                "children": "/rest/api/content/983041/child",
                "restrictions": "/rest/api/content/983041/restriction/byOperation",
                "history": "/rest/api/content/983041/history",
                "body": "",
                "version": "",
                "descendants": "/rest/api/content/983041/descendant"
            },
            "_links": {
                "self": "https://crestdatasys-team-o5vdd7bm.atlassian.net/wiki/rest/api/content/983041",
                "tinyui": "/x/AQAP",
                "editui": "/pages/resumedraft.action?draftId=983041",
                "webui": "/spaces/space1/pages/983041/page+3"
            }
        }
```

**Comment by akanshi-elastic** [comment]
and this is how we are returning it into elastic document:
![Screenshot (260)](https://github.com/elastic/connectors/assets/125074214/6b7afe4d-fa34-44a2-a9fe-591e23c7026e)

**Comment by seanstory** [comment]
I think an automation would have a hard time parsing `space1 Home page 3 page 4 child of 3` into is component parts again. Let's leave it as a list of objects, but just remove the extra noise for now (keeping only the title subfield). I've left a similar comment on your PR.
