### ISSUE TITLE
JIRA connection: actual JIRA Key is missing, please add

### ISSUE THREAD

**Issue by Gleb-Gadyatskiy** [elastic/connectors#2387]
### Problem Description
When JIRA connector imports Issues from JIRA - it concatenate Project name + Issue Key as "id" field. And the original JIRA key is not stored separately, which makes harder to get it. 

Please store JIRA Issue Key as a separate field.

### Proposed Solution
[/app/connectors/sources/jira.py](https://github.com/elastic/connectors/blob/main/connectors/sources/jira.py#L879)
Please add
`"Key": issue.get("key"),`

and JIRA key will be stored in separate field

**Comment by danajuratoni** [comment]
Have you tried using [Ingest Pipelines](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html) to extract the `id` into a new field?

**Comment by moxarth-elastic** [comment]
@Gleb-Gadyatskiy we've addressed your issue. Feel free to try it out and provide your feedback.

**Comment by Gleb-Gadyatskiy** [comment]
Works like a charm, thank you!
