### ISSUE TITLE
github 403 not being caught as an UnauthorizedError

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#2397]
Part of https://github.com/elastic/connectors/issues/2393

### Description

The github connector currently is written such that we imply that we'll re-raise authorization errors:

https://github.com/elastic/connectors/blob/8c8d4a3f7775c6edbb598a81a2b67348a7244f3a/connectors/sources/github.py#L1371-L1377

However, it seems that the error being raised in the case of a 403 is not `UnauthorizedException`, but something else, because this 403 error clearly made it to the final `except` block:

```
06:39:29.252
enterprise_search.connectors
[enterprise_search.connectors][warning] Something went wrong while fetching the issues. Exception: 403, message='Forbidden', url=URL('https://api.github.com/graphql')
  File "/usr/share/enterprise-search/lib/python3.10/site-packages/connectors/sources/github.py", line 1542, in _fetch_issues
    async for response in self.github_client.paginated_api_call(
```

### Acceptance Criteria
- [ ] github connector catches the right Exception class to handle authorization issues

**Comment by parthpuri-elastic** [comment]
@seanstory, Currently, the connector only raises an `UnauthorizedException` when the status code is `401`. So, to resolve this issue, can we also raise a Forbidden(403) exception?

**Comment by seanstory** [comment]
Ah, my mistake.

Yes, let's treat 403's and 401's the same here. They should indicate that there is a configuration issue with the connector, and the authentication provided isn't sufficient for the connector to be successful. We should fail-fast in such cases.

**Comment by khushbu-elastic** [comment]
@seanstory Could you share more information on how to reproduce this issue? If there is a specific case for verifying the issue, please let us know so that we can verify it accordingly. 
Or it would be great if you can share the configuration details with we can easily verify.
