### ISSUE TITLE
GraphQL connector: rename graphql_object_list to sth more meaningful

### ISSUE THREAD

**Issue by jedrazb** [elastic/connectors#2420]
### Problem Description

`graphql_object_list` RCF used to refer to a comma-separated list of objects from graphql response that we want to index. 

Now, instead we provide a mapping between those objects and their respective id field, this looks like
```
{
  "path.to.object.in.response": "object_id_field",
  ...
}
```

`graphql_object_list` doesn't desribe this well, and might be misleading, let's rename it to e.g. `graphql_object_to_id_map` so that it describe the variable better

**Comment by danajuratoni** [comment]
@jedrazb what label did you have in mind for the new name?

**Comment by jedrazb** [comment]
> @jedrazb what label did you have in mind for the new name RCF? Or is this only affecting internal variables?

@danajuratoni This is affecting `graphql_object_list` RFC field with label `GraphQL Objects to ID mapping`, see reference: https://github.com/elastic/connectors/blob/main/connectors/sources/graphql.py#L378
