### ISSUE TITLE
[8.14 QA] Validate Notion Connector

### ISSUE THREAD

**Issue by khushbu-elastic** [elastic/connectors#2448]
## Non-regression QA

- [ ] Notion

**Note:** always test with the latest Build Candidate on Elastic Cloud, using the full Elastic stack

- [ ] Start the whole stack from scratch and navigate to Enterprise Search
- [ ] Check that no indices are shown in the top level Indices list
- [ ] Click on "Create an Elasticsearch index" - a new page is open where you can select an ingestion method
- [ ] Choose Connector -> Use a connector
- [ ] Choose the connector you want to test and Continue
- [ ] Create an index with a valid name and Universal language
-------

- [ ] Connector name and description are editable on the Configurations page
- [ ] Connector can be deleted from the Indices page
- [ ] Connector can be deleted from the Indices page and it can be recreated with the same name after
- [ ] Pull connectors repository, run `make install` but do not run connector yet

- [ ] Verify that you are redirected to "configuration" page where you can create an api key and can copy connector id / whole section of config into the connector
- [ ] Update connector configuration with the api_key and connector_id, plus choose a service_type to test and set it in config
- [ ] Start the connector by running `make run` - verify that it starts and does not actually do anything yet
- [ ] Wait for the Kibana page with the connector configuration to update and verify that it's possible to edit connector configuration now
- [ ] Edit and save connector configuration, then reload the page and verify that configuration is properly saved
- [ ] Click on "Set schedule and sync" and verify that you're redirected to the scheduling tab
- [ ] Enable scheduling for frequency = every minute and save schedule; refresh the page and verify that the changes were stored
- [ ] Switch to the connector and wait for a minute or two, verify that connector starts to ingest data
- [ ] Verify that the data from the connector appears in the expected index
- [ ] Verify that on the index list page index information is updated properly, showing expected number of documents and new index size
- [ ] Verify that on the connector overview page "Document Count" is updated to reflect the number of documents in the index
- [ ] Verify that you can see ingested documents in `documents` tab
- [ ] Verify that index mappings are correct on the `index mappings` tab

**Record a short demo showing the connectors' configuration and that there were documents ingested**

**Comment by kajal-elastic** [comment]
@DianaJourdan @danajuratoni For Notion as Native Connector in 8.14 for Elastic Deployment 8.14.0 , there seems some configuration mismatch .
The configuration displayed in UI are :

![notion-config](https://github.com/elastic/connectors/assets/152139266/740bdb32-887e-4da1-8440-9adb69123eaf)
Expected Notion Configuration Parameters are: notion_secret_key, pages, databases , Enable Indexing comments

This needs to be updated in UI for Notion as native connector.

**Comment by seanstory** [comment]
@khushbu-elastic this means that when there were changes to the Rich Configurable Fields in the Notion Connector, they were not updated in Kibana per our [PR Checklist](https://github.com/elastic/connectors/blob/main/.github/PULL_REQUEST_TEMPLATE.md). 

Can you make the necessary PR to Kibana to align the Rich Configurable Fields? Or create an issue to do so, and assign it to someone on your team?

**Comment by praveen-elastic** [comment]
Hey @seanstory, Notion was not a native connector until now, so we wasn't anything from configurations to be added/updated in Kibana. 
I took a look at the [PR](https://github.com/elastic/kibana/pull/181153) from @efegurkan that added Notion to native and found the misconfiguration originated from [here](https://github.com/elastic/kibana/pull/181153/files#diff-2fd6806f8e6d661a999351e5f18d682c4422679416bf0067709500724f343d6bR2811). It seems like the configurations of OneDrive (tenant_id, client_id, secret_value etc.) and not that of Notion.

**Comment by seanstory** [comment]
Gotcha. Can you make a PR to correct it, or create an issue to correct it?

**Comment by khushbu-elastic** [comment]
@DianaJourdan We have checked for Notion as a Native connector by creating a new deployment on gcp-us-west2 under 8.14.0(latest) but the issue still persists and the configuration parameters are still mismatched. PFA.

![latest bc1](https://github.com/elastic/connectors/assets/133654004/1bf81985-cbaa-4ccf-b212-7729535eb4ea)

**Comment by praveen-elastic** [comment]
> @khushbu-elastic , @praveen-elastic with the [PR](https://github.com/elastic/kibana/pull/182920) this should be fixed in the last BC. Could you please try and test it again?

I think the backport PR for the same is yet to be merged on kibana for the fix to be available on 8.14, https://github.com/elastic/kibana/pull/182969. Can you please check if that might be the reason ?
