### ISSUE TITLE
Missing Issue/Pull request Author information for Github connector

### ISSUE THREAD

**Issue by gcasar** [elastic/connectors#2451]
### Problem Description

Author field is missing from Issues & Pull requests.

### Proposed Solution

Add the field to the GraphQL queries:

https://github.com/elastic/connectors/blob/50975dd795029deb131a940fb52af2e3e62a27fe/connectors/sources/github.py#L196-L201

https://github.com/elastic/connectors/blob/50975dd795029deb131a940fb52af2e3e62a27fe/connectors/sources/github.py#L287-L292

Eg,

```
        createdAt,
        author{
          login
        }
```

**Comment by navarone-feekery** [comment]
@gcasar thanks for submitting this issue.

I've added the `author.login` value to issue and pull request docs, it will be available from version v8.14.0+.
