### ISSUE TITLE
Confluence connector: Please import Confluence page labels for each page

### ISSUE THREAD

**Issue by Gleb-Gadyatskiy** [elastic/connectors#2453]
### Problem Description
It is possible to assign labels to each Confluence page. This labels can be used to identify purpose of the page. For example "kb" - for "Knowledgebase"  pages.

### Proposed Solution
Import labels for each page in Confluence connector and put them in a separate field or in "tags"

It allows to filter imported pages later. For example, I'd like Confluence pages with label "kb" be copied later in Elastic AI Assistant Knowledgebase.

**Comment by Gleb-Gadyatskiy** [comment]
REST API to use https://docs.atlassian.com/atlassian-confluence/REST/6.6.0/#content/{id}/label-labels

**Comment by danajuratoni** [comment]
@praveen-elastic please make sure importing labels is configurable as a RCF, and users opt-in when they want to sync labels.

**Comment by praveen-elastic** [comment]
Yes, we have added a configurable field for that: https://github.com/elastic/connectors/pull/2549, once this is merged, we'll raise a PR on kibana to update the RCF.

**Comment by Gleb-Gadyatskiy** [comment]
Tested - works great, good job!
