### ISSUE TITLE
Azure Blob Storage connector does not correctly clean up RAM during its work

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors#2465]
## Bug Description
There were reports that usage of Azure Blob Storage connector on Cloud creates problems with RAM on the host - syncs never end and eventually crash with Out of Memory. Looking at host RAM, memory is never recycled, even though in logs all documents are ignored in an incremental sync. So connector keeps documents in-memory and never seems to release them until end of sync.

### To Reproduce
1. Create an Azure Blob Storage connector and connect it to a reasonably large Azure Blob Storage instance
2. Run connector and observe RAM usage for the connector
3. See that memory is not released until the sync ends

## Expected behavior
Memory is released throughout the sync.

**Comment by ppf2** [comment]
@artem-shelkovnikov Until this is addressed, do we have any guidance for users to help estimate the amount of RAM required to keep the documents in memory?  For example, should they use something like the [Storage explorer](https://techcommunity.microsoft.com/t5/azure-paas-blog/calculating-container-level-stats-in-azure-blob-storage/ba-p/3064312) to add up the total blob size of all the containers configured for the connector job as a reference?  Thx!

**Comment by artem-shelkovnikov** [comment]
@ppf2 for now it's a little hard to estimate. For now I assume the amount of RAM used is equal to sum of sizes of responses from ABS API without file content (problem happens even if users run syncs that pull no file content).

We can take a look at average size of an object returned from ABS and do calculations, if needed. That can give us some formula that requires only knowing how many objects are there, theoretically.

However, it's just a theory, and we'll need more serious investigation to confirm this and adjust the numbers
