### ISSUE TITLE
Confluence Native Connector : If the type is "page", then the body section is empty, while other types are not.

### ISSUE THREAD

**Issue by anandanug** [elastic/connectors#2468]
## Bug Description
When I try to retrieve data from Confluence Cloud for the "page" type, I always find that the body section is always empty. However, when I try another type, such as "attachment", the body section always contains the content. I cannot find any error messages or additional information that can help me understand this problem further. I suspect that this may be a bug.

### To Reproduce
1. Using Confluence Native Connector
2. Sync the data

## Expected behavior

If the data type is "page", then the body section should contain the text that is inside the Confluence page.

## Screenshots

If the type is "page"

![image](https://github.com/elastic/connectors/assets/71080135/96b7fd05-2230-453d-a716-1d062f1badce)

If the type is "attachment"

![image](https://github.com/elastic/connectors/assets/71080135/3c783ac8-df23-4aa5-9fc9-b38b47e22e6d)

## Environment

- OS: Windows 11 Pro
- Browser Chrome : Version 124.0.6367.91 (Official Build) (64-bit)
- Elastic Version : Version 8.12.0

**Comment by khushbu-elastic** [comment]
@anandanug  We tried reproducing the issue but seems not reproducible at our end as the content from Confluence page is getting extracted & displayed in body tag of the index. 
PFA for the same.

![page content in index](https://github.com/elastic/connectors/assets/133654004/d77756dc-cf59-4060-a2ee-e2843b3e61d3)

![page content in confluence1](https://github.com/elastic/connectors/assets/133654004/c2e683e8-e63e-4770-8b9c-5225a9d57b17)

If the usecase is different please elaborate.

**Comment by khusbukotecha-crest** [comment]
@anandanug Please let us know if your are still facing the issue or else we can close this issue.

**Comment by khushbu-elastic** [comment]
@anandanug Please let us know if your are still facing the issue or else we can close this issue.

**Comment by anandanug** [comment]
issue has been solved. thanks for your help
