### ISSUE TITLE
[SharePoint Server] To add Created By and Modified By name instead of just AuthorId/EditorId

### ISSUE THREAD

**Issue by hiilmiee** [elastic/connectors#2504]
### Problem Description
Unable to get the file Creator/Editor name from the existing LIST_ITEM Rest API. 

### Proposed Solution
To add APIs to get Created By and Modified By name
```
{site_url}/_api/Web/Lists(guid'{list_id}')/Items({id})/File?$expand=Author&$select=Name
{site_url}/_api/Web/Lists(guid'{list_id}')/Items({id})/File?$expand=Modified&$select=Name
```

**Comment by artem-shelkovnikov** [comment]
As reported by the customer:

> the fix that was done for this only show author and editor for type : list_item but not File or Folder

Can we make sure that this change adds author/editor for all entities?
