### ISSUE TITLE
[Service Now] - Add "Time" and "Tasks" as supported services

### ISSUE THREAD

**Issue by gbocchini** [elastic/connectors#2512]
### Problem Description
Currently, the [ServiceNow Connector](https://www.elastic.co/guide/en/enterprise-search/current/connectors-servicenow.html#connectors-servicenow-configuration) supports out of the box only the following services: `User, Incident, Requested Item, Knowledge, Change Request`.

This issue would implement the possibility of ingesting info from other services like “Time” and “Tasks”.

### Proposed Solution
Add “Time” and “Tasks” and supported services out-of-the-box for the ServiceNow connector.

**Comment by praveen-elastic** [comment]
Hi @gbocchini, we were able to find "Task" service, and able to sync info from it. However, we are unable to locate "time" service. Can you please elaborate what exactly is the time service ?

**Comment by gbocchini** [comment]
Hey @praveen-elastic , will ask the customer to provide a sample/print screen! :D

**Comment by praveen-elastic** [comment]
Got it, I checked with the developer of this connector, quoting his words:

"This looks like a custom table. As the connector supports custom tables, in order to sync custom table, you need to mention that table name explicitly in configured services. 

Note: configuring `*` in the services will only fetch default tables(services): `User, Incident, Requested Item, Knowledge, Change Request.`. If a custom service is configured, any of the default table won't be fetched unless you mention those table names too in the configuration.

**Comment by gbocchini** [comment]
Niiiiiice! Didn't know! Will KB this one! Might be useful for others! :)

**Comment by ppf2** [comment]
>Note: configuring * in the services will only fetch default tables(services): User, Incident, Requested Item, Knowledge, Change Request.. If a custom service is configured, any of the default table won't be fetched unless you mention those table names too in the configuration.

Thanks! Is the behavior of `*` (i.e. it does not pick up custom objects/tables) consistent across all connectors that allow the use of `*`?  Can we identify all the connectors that share the same behavior?  It will be helpful to get this behavior documented for each affected connector.  @praveen-elastic @seanstory @leemthompo

**Comment by ppf2** [comment]
Thanks, created a PR against ServiceNow documentation only: https://github.com/elastic/enterprise-search-pubs/pull/4466

**Comment by leemthompo** [comment]
@praveen-elastic we found the explanation above slightly unclear, could you clarify which of these wordings is correct? Thx!

1. If you have configured a custom service, the `*` value will not fetch data from the basic services above by default. In this case you'll need to mention these service names explicitly.

2. `*` will only fetch the list of basic services listed above. If a custom service is configured, you must explicitly include the custom service name in the configuration as well.

**Comment by praveen-elastic** [comment]
Hey, @leemthompo  the first one sounds correct.

**Comment by praveen-elastic** [comment]
Marking this as completed, feel free to reopen if there are any concerns
