### ISSUE TITLE
Native Salesforce connector hits MalformedConfigurationError

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#2566]
## Bug Description
<img width="737" alt="connector-error" src="https://github.com/elastic/connectors/assets/5288246/0e273483-957b-4eb8-9284-02b65aadf909">

The native salesforce connector definition is missing the `use_document_level_security` config. See 
https://github.com/elastic/kibana/blob/8e911818b7ddb2622e343d76fe5249674d7d60c6/packages/kbn-search-connectors/types/native_connectors.ts#L3952-L4041

It looks like https://github.com/elastic/connectors/pull/2022 missed its corresponding Kibana PR

### To Reproduce
1. Create a native salesforce connector in 8.13.x
2. Fail to be able to configure it successfully

## Expected behavior
Kibana should define the native connector configs

## Environment
8.13.x, 8.14.0

### Workaround
Get the connector's ID, and make this elasticsearch API call:
```
POST .elastic-connectors/_update/<connector-ID>
{
  "doc":{
    "configuration":{
      "use_document_level_security": {
        "depends_on": [],
        "display": "toggle",
        "tooltip": "Document level security ensures identities and permissions set in Salesforce are maintained in Elasticsearch. This enables you to restrict and personalize read-access users and groups have to documents in this index. Access control syncs ensure this metadata is kept up to date in your Elasticsearch documents.",
        "default_value": null,
        "label": "Enable document level security",
        "sensitive": false,
        "type": "bool",
        "required": true,
        "options": [],
        "validations": [],
        "value": false,
        "order": 5,
        "ui_restrictions": []
      }
    }
  }
}
```

**Comment by moxarth-elastic** [comment]
Closing this issue since the [PR](https://github.com/elastic/kibana/pull/183600) is merged to Kibana main.
