### ISSUE TITLE
Github Sync job gets terminated if the API token is rate limited at start

### ISSUE THREAD

**Issue by gcasar** [elastic/connectors#2572]
## Bug Description
Given a github API token that is reused in another place and has its rate limits hit
When a new Sync job is triggered it will be terminated by the orchestrator

### To Reproduce
1. Use a Github token to sync a large repository
2. Once the Token has hit the rate limit create a new connector with the same one and schedule a sync job
3. After about 5 minutes the job will be terminated and marked as failed

## Expected behavior
Sync job should wait for data to start coming in, observing rate limits and not terminated by the scheduler.

## Environment
8.13.2, using a Github cloud native connector

**Comment by praveen-elastic** [comment]
Thanks for reporting this issue. @parthpuri-elastic will work on it and try to resolve this

**Comment by parthpuri-elastic** [comment]
Yes, working on it

**Comment by khushbu-elastic** [comment]
@gcasar We tried to reproduce the issue but it is working as expected and the issue is not reproducible.
We waited till the retry time (as mentioned in the logs) and successfully able to complete the sync.
Attaching the log file for reference.

[github.log](https://github.com/elastic/connectors/files/15434134/github.log)

**Comment by gcasar** [comment]
Thank you for looking into this! Peeking at the logs you seem to be using the connector version 8.14 which is not yet available for the cloud. I'll try to reproduce it once the release happens👍

**Comment by khushbu-elastic** [comment]
@gcasar Is there any update on this issue? Please let us know so that we can update the status accordingly.
CC: @seanstory

**Comment by seanstory** [comment]
This seems like it should be easy to mock, if not reproduce. I'd expect the problem is around `ping()` raising an error. 
I'm not sure that this is a bug though. If you can't establish a connection during setup, I think the error state is the right place to be. In this scenario, it failed fast to let you see that two connectors were sharing a rate limit, which is probably not what you want, right @gcasar ?

**Comment by gcasar** [comment]
@seanstory I don't necessarily disagree! My counter argument would be that since the nature of the failure is intermittent - we know we can recover and have the process for it in other places - the start of the sync should not be an exception. In the use-case of scheduled syncs this would have the implication of delaying the sync for whatever amount of time the schedule is set for. 

I'm upgrading reproducing this issue now so will update the ticket shortly and will be checking in if this is revisited as a feature so we can handle it correctly on our end :)

**Comment by gcasar** [comment]
I am able to reliable reproduce it on 8.14.3, although the way its handled did change - now it immediately errors out with a new exception that I haven't encountered before: `API rate limit exceeded for user ID 2477157`, marking the sync job as errored. Let me know how you decide to move forward.

**Comment by moxarth-elastic** [comment]
@gcasar can you please share the logs where this error has encountered to investigate further?

**Comment by gcasar** [comment]
The following is filtered with `event.dataset: (NOT "elasticsearch.gc" AND NOT "kibana.log" and NOT "enterprise_search.filebeat") and labels.index_name:"search-github-527dcb2"`

The token used was rate limited which is something that is fairly easy to achieve - point a connector to a large repository and it should get rate limited in the next 20 minutes.

What stood out to me is that the errors are not attached to the sync job & they continue after the sync job is terminated.

[Error logs for errored startup.csv](https://github.com/user-attachments/files/16519330/Error.logs.for.errored.startup.csv)

I exported the logs using a filter to remove some possibly sensitive data, if we'd want more details I can provide them in a support ticket so you can access the cloud instance.

**Comment by moxarth-elastic** [comment]
> The following is filtered with `event.dataset: (NOT "elasticsearch.gc" AND NOT "kibana.log" and NOT "enterprise_search.filebeat") and labels.index_name:"search-github-527dcb2"`
> 
> The token used was rate limited which is something that is fairly easy to achieve - point a connector to a large repository and it should get rate limited in the next 20 minutes.
> 
> What stood out to me is that the errors are not attached to the sync job & they continue after the sync job is terminated.
> 
> [Error logs for errored startup.csv](https://github.com/user-attachments/files/16519330/Error.logs.for.errored.startup.csv)
> 
> I exported the logs using a filter to remove some possibly sensitive data, if we'd want more details I can provide them in a support ticket so you can access the cloud instance.

Thanks for sharing the log file!
We've raised a PR for that will fix this issue - https://github.com/elastic/connectors/pull/2711.

**Comment by gcasar** [comment]
Thank you for the fast response! I see that PR has the 8.16 label attached to it - do you happen to know the timeline for that one/will it get backported to 8.15?

**Comment by moxarth-elastic** [comment]
> I see that PR has the 8.16 label attached to it - do you happen to know the timeline for that one/will it get backported to 8.15?

We're trying to merge this PR asap. we'll let you know once the connector is ready for you to use.

**Comment by moxarth-elastic** [comment]
> I've added a v8.15.x label so that it'll get backported too. @moxarth-elastic we should remember to always backport bugfixes to the most recent minor, if possible. Stack 8.16.0 is probably a few months away, and we don't want to make @gcasar wait that long, as having the fix in `main` doesn't necessarily mean that customers can _use_ it.

Noted. Thanks for adding a label in the PR!

**Comment by seanstory** [comment]
@gcasar the fix has been backported to 8.15. Do you need a new release (tag/docker image) or are you running from source (in which case you can `git pull origin 8.15`)?

**Comment by seanstory** [comment]
Ah. 8.15.1 release then. :)
