### ISSUE TITLE
Additional Confluence connector fields

### ISSUE THREAD

**Issue by gcasar** [elastic/connectors#2573]
### Problem Description
Key fields from Confluence documents are missing, such as the document Author and Updated date.

### Proposed Solution
Pipe all fields from the confluence response and have the query filter or an ingest processor pipeline normalize the data - more power to the user of the feature.

### Alternatives

Simply add more missing fields:
- Last modified date
- Creator / attribution
- Created date (might already be there via the `_timestamp` field

This enhancement request is related to your Confluence Cloud connector.

**Comment by danajuratoni** [comment]
@gcasar Thanks for filing the enhancement! The last modified date is already indexed in the documents, `creator` and "created date" are fields that makes sense to have. 
Are you interested in guidance on customizing the confluence connector, or only these 2 particular fields?

**Comment by gcasar** [comment]
I'll reach out to support for guidance - we've been using the[ Redact  processors](https://www.elastic.co/guide/en/elasticsearch/reference/current/redact-processor.html) to normalize data.

Adding those fields would be great 🙌 Thank you for the fast response
