### ISSUE TITLE
Opentext documentum connector has bugs and won't work

### ISSUE THREAD

**Issue by mcolak** [elastic/connectors#2607]
## Bug Description
The API part is missing; it couldn't find the documents. Normally, it must use the cabinet, but it doesn't use the cabinet; it only looks for repositories.

**Comment by seanstory** [comment]
I've added the empty template back, @mcolak to make it easy for you to see what needs to be filled out. 🙏

**Comment by moxarth-elastic** [comment]
@mcolak can you please update the description as per the template Sean has added?

**Comment by prashanttest-elastic** [comment]
@seanstory Can we close this issue for now as we are not providing the support for Opentext for now?

**Comment by khushbu-elastic** [comment]
@seanstory Can we close this issue for now, as we are not providing the support for Opentext?

**Comment by seanstory** [comment]
Yes, since https://github.com/elastic/connectors/pull/2670 was merged, this is no longer relevant.
