### ISSUE TITLE
Cannot connect to JIRA Cloud due to ‘:’ in account id 

### ISSUE THREAD

**Issue by salyia** [elastic/connectors#2614]
## Bug Description
When using a Jira Cloud service account id that contains a ':' (colon), Jira connection fails with the following error:

`[FMWK][08:57:58][ERROR] [Connector id: xxxxx, index name: mycompany-jira, Sync job id: xxxxx] A ":" is not allowed in login (RFC 1945#section-11.1)`

### To Reproduce
1. Create  a Jira connector at `https://KIBANA_URL/app/enterprise_search/content/connectors`
2. Specify a Jira Cloud service account id that contains a ':' , e.g. 123456:SOMEUUID4 (Don't have to be a valid Jira Cloud service account id)
3. Save the configuration then click Sync (choose either Full or Incremental sync)

## Expected behavior
Connector connects to Jira and syncing starts.

## Screenshots
![image](https://github.com/elastic/connectors/assets/16318529/b4775e33-9e7b-4f97-be90-0752d4e96ce8)

## Environment
Linux

## Additional context
See screenshot

**Comment by salyia** [comment]
It seems the admin email had to be provided for service id...

**Comment by artem-shelkovnikov** [comment]
@elastic/ingestion-team is it worth to update the field name/tooltip to avoid confusion?

cc @danajuratoni

**Comment by moxarth-elastic** [comment]
Closing this issue as the PR is merged. Please feel free to re-open in case of any concern.
