### ISSUE TITLE
[SharePoint Server] Use hostname instead of IP for URL

### ISSUE THREAD

**Issue by hiilmiee** [elastic/connectors#2625]
### Problem Description
Can we have the option to use hostname instead of IP Address for URL? My connector configuration only accepts IP, but would like to show hostname in the metadata

**Comment by seanstory** [comment]
Hi @hiilmiee thanks for filing.

I'd expect hostname to work already. See the docs here: https://www.elastic.co/guide/en/enterprise-search/current/connectors-sharepoint.html#connectors-sharepoint-configuration

Have you checked if it's a DNS issue? If you shell into the host/container where the connector is running, can you `curl` or `ping` the hostname of your Sharepoint Server, or do you need to use the private/local IP? The connector can't access anything that the machine/container it runs on cannot access.

**Comment by hiilmiee** [comment]
Hi @seanstory ,
apologies for the late reply.  when i entered the hostname instead of IP address, i got a warning

> [FMWK][18:45:31][WARNING] Retry count: 1 out of 3. Exception: Expecting value: line 1 column 1 (char 0)
> [FMWK][18:45:35][WARNING] Retry count: 2 out of 3. Exception: Expecting value: line 1 column 1 (char 0)
> [FMWK][18:45:43][WARNING] Retry count: 3 out of 3. Exception: Expecting value: line 1 column 1 (char 0)

and the sync job failed. i was using https://<hostname> and SSL is disabled.

**Comment by seanstory** [comment]
>  i was using https:// and SSL is disabled.

Ah, yeah I could see that causing you problems. :) I'll go ahead and close this then, if you've been able to move forward by correcting that mistake.
