### ISSUE TITLE
In the github connector, for Access Control Sync, allow_access_control field is missing for the document indexed.

### ISSUE THREAD

**Issue by khushbu-elastic** [elastic/connectors#2682]
## Bug Description
In the github connector, for Access Control Sync, allow_access_control field is missing for the document indexed.

### To Reproduce

1. Go to elasticsearch and create the Customized Connector for Github connector.
2. Set the service_type & connector_id in config.yml and make sure that DLS flag is enabled for the organizational repository.
3. Run the connector with make run command.
4. Execute the Access Control Sync from the UI and then Full Sync.
5. Check for the _allow_acess_control field in the documents indexed.

## Expected behavior
Indexing should work flawlessly along with Document Level Security functionality. _allow_access_control field should be there in all the documents indexed.

## Screenshots
![allow access control field missing](https://github.com/elastic/connectors/assets/133654004/e4cc7237-aca0-4c6a-ac55-3c7bb55ca2aa)

## Environment
- OS: Alma Linux8
- Browser Chrome
- Version 126.0.6478.127 
- Elastic v8.14.0

## Additional context
DLS working fine in the older commit https://github.com/elastic/connectors/commit/2ce504e547bde2c1a8d0a26f51fbf436de4cc826 and it is not working in the current main branch.

**Comment by khushbu-elastic** [comment]
@seanstory @artem-shelkovnikov We checked this issue in details and came to know that for private repositories, we are able to index _allow_access_control field but for public repositories, it is not working.
In older commit 2ce504e(https://github.com/elastic/connectors/commit/2ce504e547bde2c1a8d0a26f51fbf436de4cc826) _allow_access_control was getting indexed for public repositories too.
So as it is now removed from the public repositories, is it the expected behavior or should we change back the _allow_access_control field for public repositories.
Please let us know your opinion.

**Comment by parthpuri-elastic** [comment]
I took a look and I believe it makes sense. @wangch079 removed _access_control field from public repository document as those are accessible to everyone so it must be visible to all. This can be achieved by removal of _allow_access_control field.

**Comment by seanstory** [comment]
😌 ok yes, that does make sense. I'd thought this issue was reporting that they were missing from _all_ documents, but from _public_ documents only, that's ok and expected.

**Comment by khushbu-elastic** [comment]
@seanstory Okay, as it is expected behavior for the public repository, I am closing this issue with this comment as no further action is required on this. 
_allow_access_control field is visible in all the documents of other repositories than public repository, and this is the expected behavior.
