### ISSUE TITLE
Retirement of Office 365 connectors within Microsoft Teams

### ISSUE THREAD

**Issue by Socengineer** [elastic/connectors#2683]
### Problem Description
Referring to https://www.elastic.co/guide/en/kibana/current/teams-action-type.html#configuring-teams
Today in teams a message was automatically posted below a webhook message:

> Action Required: O365 connectors within Teams will be deprecated and notifications from this service will stop. [Learn more](https://aka.ms/O365ConnectorDeprecation)" about the timing and how the Workflows app provides a more flexible and secure experience. If you want to continue receiving these types of messages, you can use a workflow to post messages from a webhook request. 

Quoted from the article: 
> Starting August 15th, 2024 we will be retiring the Office 365 connectors feature from Microsoft Teams

Included with this message was a link to set up a workflow for the teams channel in question. Running through the wizard is easily enough and you end up with a URL that can be posted into the webhook URL field in elastic connectors config. 

Testing this in Kibana shows successful test, but on the Microsoft side a failure is reported, referring to null data being received. 

### Proposed Solution
Validate together with Microsoft what actions are required from your side in regards to sending the webhook data.

### Alternatives
Update elastic documentation to reflect how to correctly implement a workflow in replacement of the deprecating Teams connector.

### Additional context

![image](https://github.com/elastic/connectors/assets/94682062/fa263b95-8f3f-4753-bf7e-7e5b9a64b4ed)

![image](https://github.com/elastic/connectors/assets/94682062/a5e47dee-61da-406f-b717-d42b5efa10c9)

**Comment by seanstory** [comment]
Hi @Socengineer  - thanks for filing, but I think you've got the wrong repo. This repository is for [Elastic Connectors](https://www.elastic.co/guide/en/enterprise-search/current/connectors.html), but it sounds like your enhancement request is for [Kibana Connectors](https://www.elastic.co/guide/en/kibana/current/action-types.html) (🙈 naming is hard).

I suggest filing your issue instead at https://github.com/elastic/kibana
