### ISSUE TITLE
Postgres advanced sync rules missing in Native Connectors

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#2686]
## Bug Description
https://github.com/elastic/kibana/blob/dd9d6434cae8b7beb3b730cd42898b8f63dbee91/packages/kbn-search-connectors/types/native_connectors.ts#L3867 specifies that Advanced Sync Rules for the Postgres Native Connector are disabled. But these should have been enabled as part of https://github.com/elastic/connectors/pull/1691 for 8.11

### To Reproduce
- create a postgres native connector
- try to add advanced sync rules

## Expected behavior
Advanced Sync Rules should be available

## Screenshots
![image](https://github.com/elastic/connectors/assets/5288246/be1db37e-2091-4d7b-846c-18da9813dd22)

## Environment
8.11-8.14

## Workaround
Get the connector's ID. You can find this by doing a `GET .elastic-connectors/_search` and looking for the right connector. Then execute the below Elasticsearch request, replacing `<connector_id>` with your connector's ID.

```
POST .elastic-connectors/_update/<connector_id>
{
  "doc": {
    "features": {
      "sync_rules": {
        "advanced": {
          "enabled": true
         }
      }
    }
  }
}
```

**Comment by praveen-elastic** [comment]
> But these should have been enabled as part of https://github.com/elastic/connectors/pull/1691 for 8.11

@seanstory back in September, 2023 when this PR for Postgres https://github.com/elastic/connectors/pull/1691 got merged there was no checklist that stated raising a PR on Kibana for native connector changes. The Checklist item might have been introduced later. Before that, the changes to Kibana files was being taken care by Elastic.

However, we're happy to fix this.

**Comment by praveen-elastic** [comment]
Upon further investigation it was found that some more connectors were having similar issue. This was determined by checking which connectors has support for Advanced sync rules from: https://github.com/search?q=repo%3Aelastic%2Fconnectors%20advanced_rules_enabled%20%3D%20True&type=code

**Comment by praveen-elastic** [comment]
Upon further investigation it was found that some more connectors were having similar issue. This was determined by checking which connectors has support for Advanced sync rules using: https://github.com/search?q=repo%3Aelastic%2Fconnectors%20advanced_rules_enabled%20%3D%20True&type=code

cc @navarone-feekery
