### ISSUE TITLE
'_asyncio.Task' object has no attribute 'name'

### ISSUE THREAD

**Issue by Dig-Doug** [elastic/connectors#2689]
## Bug Description
Exception in connector logs:

```
[FMWK][12:59:56][INFO] [Connector id: connector-id-redacted , index name: my-index] Successfully connected to Postgresql.
[FMWK][13:03:20][WARNING] Client method 'bulk' retry 1: connection timeout
[FMWK][13:03:36][WARNING] Client method 'bulk' retry 1: connection timeout
[FMWK][13:04:03][WARNING] Client method 'bulk' retry 1: connection timeout
[FMWK][13:04:31][WARNING] Client method 'bulk' retry 1: connection timeout
[FMWK][13:05:00][WARNING] Client method 'bulk' retry 1: connection timeout
[FMWK][13:06:58][ERROR] [Connector id: connector-id-redacted, index name: my-index, Sync job id: bGhMkpABVYZeIycy7pxX] Sync was throttled by Elasticsearch
[FMWK][13:07:00][ERROR] [Connector id: connector-id-redacted, index name: my-index, Sync job id: bGhMkpABVYZeIycy7pxX] '_asyncio.Task' object has no attribute 'name'
Traceback (most recent call last):
  File "/app/connectors/sync_job_runner.py", line 207, in execute
    await self._sync_done(sync_status=sync_status, sync_error=sync_error)
  File "/app/connectors/sync_job_runner.py", line 352, in _sync_done
    await self.sync_orchestrator.cancel()  # in case the extractor/sink tasks are still running
  File "/app/connectors/es/sink.py", line 887, in cancel
    f"Cancling the Sink task: {self._sink_task.name}"  # pyright: ignore
AttributeError: '_asyncio.Task' object has no attribute 'name'
[FMWK][13:07:00][INFO] [Connector id: connector-id-redacted, index name: my-index, Sync job id: bGhMkpABVYZeIycy7pxX] Job terminated. Cleaning up.
[FMWK][13:07:00][ERROR] Exception found for task Task-66: '_asyncio.Task' object has no attribute 'name'
[FMWK][13:07:02][WARNING] Client method 'bulk' retry 2: api error with status 429
[FMWK][13:07:03][WARNING] Client method 'bulk' retry 2: api error with status 429
```

### To Reproduce
I am trying to run a postgres connector to sync a few million records. This error occurs when the connector overloads the elastic search instance.

## Expected behavior
Exception should not be thrown.

## Environment
Running on docker at head.

**Comment by seanstory** [comment]
🤦 thanks for flagging. Should be `.get_name()`. IDK how I missed this.
@artem-shelkovnikov caught the same here: https://github.com/elastic/connectors/pull/2671/files#diff-68c31d9379d91378705cf6d47c447185e8c6ad952876c7a5fb979e3c89646148R914 but let's not wait for that PR to get in to fix this, especially because it looks like I backported the mistake to 8.14

**Comment by seanstory** [comment]
@Dig-Doug ☝️ will resolve the specific stack trace you're hitting. However, that's not going to make your sync succeed. Looks like your Elasticsearch instance is buckling under the load, and it's leading to the framework trying to cancel the sync orchestrator. You should consider either scaling up your Elasticsearch's resources, or lowering the bulk settings for the connector to send fewer/smaller batches of documents.
