### ISSUE TITLE
Throttle based on cluster capacity

### ISSUE THREAD

**Issue by Dig-Doug** [elastic/connectors#2702]
### Problem Description
I have been trying to use the postgres connector to upload documents to a single-node elastic cloud deployment.  When I start the connector, it runs for a while, eventually overloads the stack, and then the sync fails. I've tried many different timeout/retry configurations but nothing has worked.

### Proposed Solution
I saw that there is a [cluster stats api](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-stats.html). The connector could periodically poll the `ingest` nodes to see how much cpu/memory/disk capacity is available and wait if there is none.

**Comment by artem-shelkovnikov** [comment]
Hey @Dig-Doug,

You can change the configurations to slow down the connectors:

```
##  The max size of the bulk operation to Elasticsearch.
#elasticsearch.bulk.chunk_size: 500
#
#
##  Maximum number of concurrent bulk requests.
#elasticsearch.bulk.max_concurrency: 5
#elasticsearch.bulk.concurrent_downloads: 10
#
#
##  Retry interval between failed bulk attempts
#elasticsearch.bulk.retry_interval: 10
```

Increasing retry intervals + decreasing concurrency/batch sizes should help.

There is cluster stats API, but we should not be using it and just trust the cluster to report health problems with 429s.

**Comment by seanstory** [comment]
☝️ expanding on that - if you can show that Elasticsearch is responding with 429s and we're not correctly retrying or backing off, please let us know. But as is, we won't be planning to change the connectors to try to proactively asses and treat Elasticsearch health issues.
