### ISSUE TITLE
Network Drive connector DLS mapping CSV gives error - IndexError: list index out of range

### ISSUE THREAD

**Issue by A-Hall** [elastic/connectors#2728]
## Bug Description
When supplying a DSL mapping CSV to a connector service Docker container, you receive an error - IndexError: list index out of range

### To Reproduce
1. Create a network drive connector. - https://{kibana_URL}:5601/app/enterprise_search/content/connectors/new_connector?service_type=network_drive&connector_type=connector_clients
2. Under the configuration, enable Document Level Security and supply the path to your mapping.csv file.
3. Run an access control sync
4. The error is returned:

```
[FMWK][19:10:52][CRITICAL] [Connector id: Ymfz4JAB1oTHpHwc9jx7, index name: .search-acl-filter-network_drive, Sync job id: m3Dm_5AB1oTHpHwc6yK-] Document extractor failed
Traceback (most recent call last):
  File "/app/connectors/es/sink.py", line 494, in run
    await self.get_access_control_docs(generator)
  File "/app/connectors/es/sink.py", line 721, in get_access_control_docs
    async for doc in generator:
  File "/app/connectors/logger.py", line 247, in __anext__
    return await self.gen.__anext__()
  File "/app/connectors/es/sink.py", line 521, in _decorate_with_metrics_span
    async for doc in generator:
  File "/app/connectors/sync_job_runner.py", line 513, in generator
    async for doc in self.data_provider.get_access_control():
  File "/app/connectors/sources/network_drive.py", line 787, in get_access_control
    for user in self.read_user_info_csv():
  File "/app/connectors/sources/network_drive.py", line 750, in read_user_info_csv
    "user_sid": row[1],
IndexError: list index out of range
```

## Expected behavior
The CSV is read and DSL features configured.  

## Screenshots

![image](https://github.com/user-attachments/assets/40a8e6b8-02ce-4efa-90bd-d4f5cf45815a)

![image](https://github.com/user-attachments/assets/58e620c4-7873-454d-8c32-6f5a2dbef035)

## Environment
Using the example [csv](https://github.com/elastic/enterprise-search-network-drive-connector/blob/main/network_drive_enterprise_search_mapping/example_mapping.csv):
```
andrew@worknuc:~/connectors-config$ cat mapping.csv
sid_1_network_drives,user_1_enterprise_search
sid_2_network_drives,user_2_enterprise_search
```

- OS: Ubuntu
- Browser chrome
- Version:
  - ES/KB: 8.14.3
  - Connector service: 8.14.3.0

**Comment by moxarth-elastic** [comment]
Hi @A-Hall, this mapping csv is that of network drive connector standalone package. The new framework has a different format. Thank you for raising the issue, we'll  update the elastic docs with sample format, meanwhile here is the correct format: `name;user-sid;groups(optional comma separated list)`

```
user1;S-1;S-11,S-22
user2;S-2;S-22
``` 
Note that the delimeter is `;` and not comma for this CSV.

**Comment by moxarth-elastic** [comment]
@A-Hall did you get a chance to test the DLS with this CSV format? 

> Hi @A-Hall, this mapping csv is that of network drive connector standalone package. The new framework has a different format. Thank you for raising the issue, we'll update the elastic docs with sample format, meanwhile here is the correct format: `name;user-sid;groups(optional comma separated list)`
> 
> ```
> user1;S-1;S-11,S-22
> user2;S-2;S-22
> ```
> 
> Note that the delimeter is `;` and not comma for this CSV.

**Comment by A-Hall** [comment]
Yep, that appears to be working as expected.  Thanks for the info!

**Comment by moxarth-elastic** [comment]
> Hi @A-Hall, this mapping csv is that of network drive connector standalone package. The new framework has a different format. Thank you for raising the issue, we'll update the elastic docs with sample format, meanwhile here is the correct format: `name;user-sid;groups(optional comma separated list)`
> 
> ```
> user1;S-1;S-11,S-22
> user2;S-2;S-22
> ```
> 
> Note that the delimeter is `;` and not comma for this CSV.

@leemthompo We should add the CSV format in the [network drive documentation](https://www.elastic.co/guide/en/enterprise-search/current/connectors-network-drive.html#connectors-network-drive-client-configuration) to avoid the confusion. Can you please update the doc as follows:

### For Connector Client,

Update the `identity_mappings` under **Configuration** section

- Path of CSV file containing user and group SIDs (For Linux Network Drive).
- CSV file should contain three columns with `;` delimiter - 
   1. username
   2. user-sid
   3. groups (optional comma separated list)
- CSV file Example:
   - Example 1 with one username, user-sid and two groups
      ```
      user1;S-1;S-11,S-22
      ``` 
   - Example 2 with one username, user-sid and no group
      ```
      user1;S-1;
      ```

**Comment by danajuratoni** [comment]
@leemthompo it would be great to have this doc update for 8.16. Thanks!

**Comment by DianaJourdan** [comment]
@leemthompo , @danajuratoni is the documentation still pending or we can close it?

**Comment by leemthompo** [comment]
Still pending, I'll get this done this sprint. How far back does this apply version-wise?

**Comment by leemthompo** [comment]
@moxarth-elastic good news is that from 8.16.0 onwards the official connectors docs will live in the Elasticsearch repo which is public, so you'll be able to make patches directly there via PRs. 🎉

**Comment by leemthompo** [comment]
@moxarth-elastic updating docs right now. How far should we backport?

**Comment by moxarth-elastic** [comment]
@leemthompo we introduced DLS in network drive connector in 8.11 - https://github.com/elastic/connectors/pull/1699, so we should go back till 8.11.
cc: @danajuratoni

**Comment by leemthompo** [comment]
Docs updates have merged
