### ISSUE TITLE
[ServiceNow] Connector to support custom tables

### ISSUE THREAD

**Issue by iamhowardtheduck** [elastic/connectors#2745]
### Problem Description
Specific tables require to be ingested for a security use-cases that are not covered within the 5 supported services.  

Attempted to ingest all services which resulted in a timeout, limited the scoped to Incident as well as Requested Item with table related data not ingested.  Attempted an advanced rule which would look for anything related to one of the tables that 

### Proposed Solution
Provide URL(s) specific to the table(s) which require to be ingested, and have synchronization jobs pull from the URL(s)> 

### Alternatives
Download data to S3 bucket and ingest to Elastic, while viable, breaks requirements from the security team as the data is highly sensitive.

### Additional Context
![image (24)](https://github.com/user-attachments/assets/78df8fe9-b7dd-40a2-85e6-c803458ac39d)

**Comment by seanstory** [comment]
Hi @iamhowardtheduck , did you try specifying your custom tables in the configuration for "comma-separated list of services"? See this note in [the docs](https://www.elastic.co/guide/en/enterprise-search/current/connectors-servicenow.html#connectors-servicenow-configuration):

> If you have configured a custom service, the * value will not fetch data from the basic services above by default. In this case you’ll need to mention these service names explicitly.

Separately, regarding:

> Attempted to ingest all services which resulted in a timeout,
> ...
> Attempted an advanced rule which would look for anything related to one of the tables

If either of these didn't work as expected, please feel free to file a Bug issue, with details around the errors you encountered.

**Comment by danajuratoni** [comment]
@iamhowardtheduck closing this, as custom tables are supported (check out Sean's comment for a link to the docs)
Please open a bug with details on the encountered errors if this doesn't work as expected.  Thanks!
