### ISSUE TITLE
[Network Drive] Document Overwrite Issue in AccessControl Sync Due to Duplicate Group SIDs

### ISSUE THREAD

**Issue by y-hozumi** [elastic/connectors#2821]
Dear Development Team,

I hope this message finds you well. I am writing to bring to your attention a potential issue we've encountered while using the AccessControl Sync feature. We believe this issue may impact the accurate representation of access control information in the system.

### Issue Description
We have observed that when multiple users belong to the same group, the AccessControl Sync process appears to overwrite documents in the `.search-acl-filter-xxx` index. This occurs because the process seems to use the end of the Group SID as the document's `_id`.

### Steps to Reproduce
1. Prepare a CSV file with the following content:
UserName;UserSid;GroupSid
user_1;S-xxx-1135;S-xxx-513,S-xxx-1139
user_2;S-xxx-1136;S-xxx-513,S-xxx-1139
2. Execute AccessControl Sync using this CSV file.
3. Examine the resulting index (`.search-acl-filter-xxx`).

### Current Behavior
The index contains only one document, despite the CSV file containing two distinct user entries.

### Expected Behavior
We would expect the index to contain two documents, corresponding to the two rows in the CSV file.

### Impact
This behavior potentially leads to loss of access control information and may prevent accurate reflection of user permissions in the system.

### Environment Details
- Connector Client: 8.15
- ElasticCloud Version: 8.14.1

### Additional Information
We've noticed that the `_id` of the document in the index corresponds to the last part of the Group SID (in this case, "1139"). This seems to cause the overwrite when multiple users share the same group.

Upon further investigation, we believe we have identified the source of this issue in the codebase. The problem appears to stem from the following section of code:
[network_drive.py#L720-L739](https://github.com/elastic/connectors/blob/main/connectors/sources/network_drive.py#L720-L739)

We would greatly appreciate your insights into this matter. If any additional information or clarification is needed, please don't hesitate to ask. We are more than willing to provide any further details that might assist in addressing this issue.

Thank you for your time and attention to this matter. We look forward to your response and any potential solutions you might suggest.

**Comment by seanstory** [comment]
Thank you for the detailed report. We'll take a look right away.
