### ISSUE TITLE
ServiceNow Washington and Xanadu compatibility check

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors#2849]
ServiceNow has released [new versions](https://www.servicenow.com/community/now-platform-articles/servicenow-versions-release/ta-p/2312014): Washington and Xanadu(early availability) that we need to check the ServiceNow's connector compatibility against.

- [x] Compatibility tests for running SNow connector against Washington
- [x] Compatibility tests for running SNow connector against Xanadu
- [x] Update documentation and add newly released versions

**Comment by khushbu-elastic** [comment]
@danajuratoni We have performed compatibility checks for ServiceNow's versions Washington and Xanadu on Elastic 8.15. 
All the functionalities of the ServiceNow connector is working as expected with both newer versions. 
The documentation for the ServiceNow connector needs to be updated accordingly.

@leemthompo  Could you please update the documentation for the ServiceNow Connector adding the support for the above mentioned versions?

**Comment by leemthompo** [comment]
PR is open: https://github.com/elastic/enterprise-search-pubs/pull/4624

**Comment by khushbu-elastic** [comment]
@leemthompo Could you please update the status for this issue if the documentation [PR](https://github.com/elastic/enterprise-search-pubs/pull/4624) is merged?
NOTE:  I could not check the same as that URL shows 404 error.
