### ISSUE TITLE
One global e2e test

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors#390]
add an e2e test that runs all connectors at the same time

TO DO: let s use this issue to cover all test flows for connectors python:
- e2e functional backend tests
- Cyprus tests with happy paths for native connectors
- performance reports

This pipeline could be run nightly

**Comment by serenachou** [comment]
all connector clients? native only?

**Comment by tarekziade** [comment]
> all connector clients? 

as discussed with @danajuratoni before: like for the single connector performance baseline, the PMs should come up with a baseline definition of what we should be able to sync simultaneously with the service. e.g. estimation of the number of concurrent syncs, and which backends -- given our deployments sizes on Cloud

> native only?

We focus on native only because we are resource-constrained on our existing Cloud. on-prem, the sizing work done for on-cloud can give our customer the info about what kind of resources they need to operate the service

**Comment by DianaJourdan** [comment]
@timgrein @artem-shelkovnikov it would be great to use this issue to test if we are capable of running more native connectors than only MongoDB and MySQL? Do we have any limitation?

@danajuratoni if we want to test more native connectors, any top list on your side?

**Comment by artem-shelkovnikov** [comment]
@DianaJourdan we have a list of connectors to test and try supporting natively here: https://github.com/elastic/enterprise-search-team/issues/4260

It's a "stretch" list - we'll try to support as many as possible.

As to limitations, our limitation currently is "number of syncs running at the same time" + estimates on how much memory each connector needs. We'll estimate the latter

**Comment by seanstory** [comment]
We have nightly tests that run every connector, and we've got other initiatives to improve the realism of those. I don't think we need this anymore. Please re-open if you disagree.
