### ISSUE TITLE
Improve base64 chunk-encoding function

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors#534]
Right now we have `convert_to_b64` that takes a file and converts it to `b64`

https://github.com/elastic/connectors-python/blob/main/connectors/utils.py#L139

in connectors, it requires each DataSource to dump the file on disk. We can have the framework do this as well, and simplify the DataSource code.

The new signature could look like this:

```python
async def chunk_encoding(data_stream):
    """
    - Iterates on `data_stream` and creates a temp  file on disk with it.
    - once the file is created, call `base64` to stream encode it
    - returns a generator with the file content
    - when exhausted, delete the file
    """
    XXX
```

From there, the sources can provide the `data_stream` generator by plugging the backend API

**Comment by tarekziade** [comment]
updated my branch here  https://github.com/elastic/connectors-python/pull/220 which implements a first version of the whole disk-based system for async chunk-based upload

**Comment by seanstory** [comment]
@navarone-feekery is this still relevant? I believe you refactored a lot of our downloading code when you worked on the data extraction service.

**Comment by navarone-feekery** [comment]
@seanstory I _think_ I've implemented something similar [here](https://github.com/elastic/connectors/pull/1685). The download is handled by source now.
