### ISSUE TITLE
NodeConfig can be misleading when it shows no ca_certs being used for a https connection

### ISSUE THREAD

**Issue by ppf2** [elastic/connectors#843]
I specified `ca_certs` setting in the `config.yml` to successfully connect to an https enabled Elasticsearch instance with a self-signed cert.  At the `DEBUG` level, it does show that it is able to verify the CA cert, but the messaging at the `INFO` level shows `ca_certs` is `None`:

```
[FMWK][17:05:30][DEBUG] Connecting using Basic Auth (user: elastic)
[FMWK][17:05:30][DEBUG] Verifying cert with /Users/<user>/Elastic/_docker/elastic-8.7/ca.crt
[FMWK][17:05:30][INFO] Preflight checks...
[FMWK][17:05:30][DEBUG] Wait for Elasticsearch (max: 120)
[FMWK][17:05:30][INFO] Waiting for NodeConfig(scheme='https', host='localhost', port=9200, path_prefix='', headers={}, connections_per_node=10, request_timeout=10.0, http_compress=False, verify_certs=True, ca_certs=None, client_cert=None, client_key=None, ssl_assert_hostname=None, ssl_assert_fingerprint=None, ssl_version=None, ssl_context=None, ssl_show_warn=True, _extras={}) (so far: 0 secs)
[FMWK][17:05:30][DEBUG] Checking for index .elastic-connectors presence
[FMWK][17:05:30][DEBUG] Checking for index .elastic-connectors-sync-jobs presence
[FMWK][17:05:31][DEBUG] ConnectorIndex connecting to https://localhost:9200/
```

The `INFO` message above can be misleading since it does not show that `ca_certs` is set.

**Comment by llermaly** [comment]
Sorry for a potential out of topic but I'm trying to use the connector service with ECK and I'm not even seeing the "verifying cert with". I'm following the Logstash recipe (Logstash works) but can't make the python connector to work. 

Do you have any reference file or advice? This is how Logstash connects to ECK:

https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/logstash/logstash.yaml
Thanks!

**Comment by seanstory** [comment]
Looks related to https://github.com/elastic/connectors/issues/1826
