### ISSUE TITLE
troubleshoot issues, error handling

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors#923]
we need better visibility on issues when pulling docs or interacting with ES.

For Elasticsearch, we want an exhaustive support of all possible errors, see for instance https://github.com/elastic/connectors-python/issues/856

For backends, one first step would be to have a standard generic set of error code, augmented with specific backend errors

**Comment by tarekziade** [comment]
- Document bulk errors - right now we are just logging reason see https://github.com/elastic/connectors-python/blob/main/connectors/es/sink.py#L135 - we should also grab the error type https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html
- 
- ES HTTP API calls - for each call we do, we need to catch every possible error and define an explicit behavior in https://github.com/elastic/connectors-python/blob/main/connectors/es/sink.py  -- we currently catch general errors, but we should surface the Elastic API error in our logs from https://elasticsearch-py.readthedocs.io/en/latest/exceptions.html#elasticsearch.ApiError with the original status code and message
-

**Comment by artem-shelkovnikov** [comment]
Additionally IMO we need to expose stats about these errors in telemetry

**Comment by DianaJourdan** [comment]
Closing this ticket, as [#5059](https://github.com/elastic/enterprise-search-team/issues/5059) should cover it and take a global approach on error handling
