### ISSUE TITLE
BadRequestError(400, 'parse_exception', 'Failed to parse content to type') appears for some attachments while Indexing

### ISSUE THREAD

**Issue by khushbu-elastic** [elastic/connectors#953]
## Bug Description
BadRequestError(400, 'parse_exception', 'Failed to parse content to type') appears for some attachments while Indexing which leads to data loss as such files are not getting indexed. They are supported file types.

### To Reproduce

Pre-requisites:
1. A project already created in Jira (server/cloud) instance
2. Create an Index in Elasticsearch
3. Mention all the required details correctly in the config.yml file and Jira configured as source

Steps:
1. Mention all the required details correctly in kibana UI as per the requirement and Enter a project key for the project available in Jira
2. For advanced sync rule, draft a query which contains attachment as result
3. Execute make run command
4. Observe the logs on console
5. Once the command execution is completed, verify if the Jira documents is indexed in Elasticsearch as per the query in sync rule.

## Actual Result:

2 of the extractable attachments get missed while indexing and BadRequestError is displayed

Log:
[FMWK][17:41:33][ERROR] Exception found for task Task-1368: BadRequestError(400, 'parse_exception', 'Failed to parse content to type')
[FMWK][17:41:37][ERROR] Exception found for task Task-1375: BadRequestError(400, 'parse_exception', 'Failed to parse content to type')

## Expected behavior
All the documents i.e. issues and attachments should be indexed as per the query in sync rule. Data loss should not happen.

## Attaching the files here, which are getting missed:

[FMWK][15:44:52][ERROR] Exception found for task Task-99: BadRequestError(400, 'parse_exception', 'Failed to parse content to type')
[FMWK][15:45:07][ERROR] Exception found for task Task-106: BadRequestError(400, 'parse_exception', 'Failed to parse content to type')
![unnamed](https://github.com/elastic/connectors-python/assets/133654004/e9553526-7756-4826-9173-1165340d0d21)

[SamplePDFFile_5mb (2).pdf](https://github.com/elastic/connectors-python/files/11562901/SamplePDFFile_5mb.2.pdf)

[SampleTextFile-9MB.txt](https://github.com/elastic/connectors-python/files/11562944/SampleTextFile-9MB.txt)
## Environment
- OS: Alma Linux 8
- Browser: Chrome
- Version: Version 113.0.5672.127

## Additional context
Note:
This issue is faced in 8-8 elastic instance and attachment indexing is working fine in 8.7

**Comment by khushbu-elastic** [comment]
We have observed that this issue seems resolved in the latest Elastic 8.8 cloud version.

@danajuratoni  Could someone from the team look into this and confirm the same? Also update the status accordingly, so that we can close this.

CC: @parth-elastic

**Comment by artem-shelkovnikov** [comment]
Probably an issue with mapping - some field in Jira can return data of different types

**Comment by seanstory** [comment]
If I understand correctly, JIRA is returing this 400 error when we try to download these attachments? In that case, this feels like a JIRA bug, not our issue.
1. 400 is the wrong error code for a parse exception on their end
2. no idea why they can't return the documents

If I'm not misunderstanding, I suggest we close this issue, I'm not sure if there's much we can do here.

**Comment by khushbu-elastic** [comment]
@seanstory We have checked for this issue and it seems working fine as those attachments are getting indexed.
Therefore, closing this issue.
