### ISSUE TITLE
multiple connector declaration in config.yml to sync multiple mongoDB collection inside one container 

### ISSUE THREAD

**Issue by DevBey** [elastic/connectors#974]
## Bug Description
while running the docker container on my local elasticsearch instance on an ec2, I am able to sync mongoDB to elasticsearch smoothly, the problem is in the config.yml, I am not able to add multiple connectors for various collection as every collection will have one connector ID. does one docker container with one config work with only one connector?? or am I missing ??anything

### To Reproduce

1. while editing config file, no way to add multiple connectors in a single config file. [https://github.com/elastic/connectors-python/blob/cb0e8f56fe7dd545fd6de0260fb33fada10fbd62/config.yml#L46)]

## Expected behavior

1. to be able to use a single docker container to perform multiple sycing for multiple connectors (mongoDB collections) ??

## Environment

- EC2
- self managed docker ELK using docker compose version 8.8
- connector version 8.9

## Additional context
only one connector works inside one container, does that mean we will need multiple containers for every connector (mongoDB collection)??

**Comment by artem-shelkovnikov** [comment]
Hi @DevBey, indeed for now one self-managed instance of connector service (or Docker image in your case) is supposed to run against single connector.

We have a plan to add support for multiple connectors running on a same instance of Connector Service later, but no concrete date unfortunately.

cc @danajuratoni

**Comment by DevBey** [comment]
Hello @artem-shelkovnikov,

Thanks for the reply, it's very sad though, as any relatively big company will have tens if not hundreds of mongo DB collections, and if for every collection we need to run one container then it becomes very cumbersome.

for instance, currently we use monstache https://github.com/rwynn/monstache for the sync from mongoDB to elasticsearch. in which case we just have to run a single container which tails the oplog for any changes in real-time. 

This reminds me of a secondary issue, as per my understanding the current mongoDB connector refreshes the whole collection repeatedly instead of tailing the oplog for various operations. As the collection size and document increase it will become dangerous to do this kind of full refreshment!

**Comment by artem-shelkovnikov** [comment]
> This reminds me of a secondary issue, as per my understanding the current mongoDB connector refreshes the whole collection repeatedly instead of tailing the oplog for various operations. As the collection size and document increase it will become dangerous to do this kind of full refresh!

That is indeed true, but we have it on our radar! I cannot promise you anything specific in terms of timelines, but we're planning to approach it and allow subscribing to changes coming through oplog as well.

> Thanks for the reply, it's very sad though, as any relatively big company will have tens if not hundreds of mongo DB collections, and if for every collection we need to run one container then it becomes very cumbersome.

I totally understand that and it's indeed the case that we don't handle that well yet.

**Comment by DevBey** [comment]
great thanks @artem-shelkovnikov, @wangch079 

are the oplog-based incremental updates also implemented ??

**Comment by wangch079** [comment]
Hi @DevBey , were you referring to the [Change Streams](https://www.mongodb.com/docs/manual/changeStreams/) for MongoDB?

**Comment by DevBey** [comment]
yep yep @wangch079 , basically instead of full refresh, just incremental live sync !!

**Comment by wangch079** [comment]
HI @DevBey , this is not implemented for MongoDB. You can add a customized [incremental sync implementation](https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md#how-an-incremental-sync-works) if you want.

**Comment by DevBey** [comment]
Hello @wangch079,

is there any plan of implementation of that here, using data stream/oplog.

**Comment by wangch079** [comment]
Hi @DevBey , unfortunately, this is not planned in the near future. As mentioned above, you can add a customized incremental sync implementation.

**Comment by seanstory** [comment]
@DevBey you may want to watch https://github.com/elastic/enterprise-search-team/issues/6468, which is related to some sweeping changes we're trying to make to support incremental syncs for more sources.

> I believe we can close this issue, as it was implemented for 8.10?

I'm going to go ahead and close this. Definitely feel free to re-open if the original issue is not resolved, or create a new issue for any new problems you encounter.
